#!/usr/bin/env python3
"""
SpectrumAnalyzer_prepare.py
=======================
Single-file bundle builder.  Run ONCE on any internet-connected machine.
Produces a ZIP that installs SpectrumAnalyzer on a fully offline machine with
NO pre-installed Python, conda, or internet access on the target.

Requirements (build machine only):
    Python 3.7+  —  standard library only, no pip installs needed

Usage:
    python SpectrumAnalyzer_prepare.py
    python SpectrumAnalyzer_prepare.py --arch aarch64    # for Raspberry Pi 4/5
    python SpectrumAnalyzer_prepare.py --clean           # fresh build

What it downloads:
    • Miniforge3 installer  (.sh on Linux, .exe on Windows)
    • All conda packages    (SoapySDR, HackRF driver, PyQt6, scipy, …)
    • All pip wheels        (FastAPI, uvicorn, websockets, …)
    • Your application source code

Output:
    SpectrumAnalyzer_bundle_linux_x86_64.zip   (built on Linux)
    SpectrumAnalyzer_bundle_linux_aarch64.zip  (built on Linux, --arch aarch64)
    SpectrumAnalyzer_bundle_windows_x86_64.zip (built on Windows)

On the offline target machine:
    Linux   →  unzip SpectrumAnalyzer_bundle_*.zip  &&  bash install.sh
    Windows →  Unzip  →  double-click install.bat
                       OR right-click install.ps1 → "Run with PowerShell"

NOTE: The bundle is platform-specific because conda environments contain
compiled native code.  Build on Linux to deploy on Linux/Pi; build on
Windows to deploy on Windows.
"""

# ─── stdlib imports ────────────────────────────────────────────────────────
import argparse
import os
import platform
import shutil
import stat
import subprocess
import sys
import textwrap
import urllib.request
import urllib.error
import zipfile
from pathlib import Path

# ═══════════════════════════════════════════════════════════════════════════
#  CONFIGURATION  —  edit only this section
# ═══════════════════════════════════════════════════════════════════════════

APP_NAME          = "SpectrumAnalyzer"
ENV_NAME          = "SpectrumAnalyzer"
MINIFORGE_VERSION = "24.3.0-0"

# Channels: ryanvolz carries SoapySDR and HackRF/USRP native modules
CONDA_CHANNELS = ["-c", "conda-forge", "-c", "ryanvolz", "--override-channels"]

CONDA_PACKAGES = [
    "python=3.11",
    "numpy>=1.24",
    "scipy>=1.11",
    "pyqt6>=6.5",
    "pyqtgraph>=0.13",
    "soapysdr>=0.8",
    "soapysdr-module-hackrf",
    "hackrf",
    "soapysdr-module-uhd",
    "conda-pack",            # must be in env so target has conda-unpack
]

# Pure-Python wheels for the FastAPI / WebSocket web layer
PIP_PACKAGES = [
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.29.0",
    "websockets>=12.0",
    "starlette>=0.37.0",
    "httpx>=0.27.0",
]

# Where the app source lives relative to THIS script
APP_SOURCE_DIR = Path(__file__).parent

# ═══════════════════════════════════════════════════════════════════════════
#  EMBEDDED INSTALLER TEMPLATES
#  These strings are written into the bundle zip as install.sh / install.ps1
# ═══════════════════════════════════════════════════════════════════════════

# ── Linux installer (bash, no dependencies needed on target) ────────────────
INSTALL_SH = r"""#!/usr/bin/env bash
# =============================================================================
#  SpectrumAnalyzer  —  Linux offline installer
#  Generated by SpectrumAnalyzer_prepare.py
#
#  Run from the directory where you unzipped the bundle:
#      bash install.sh
#
#  Requires ONLY: bash, tar, awk, find   (all standard on every Linux)
# =============================================================================
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_NAME= "SpectrumAnalyzer"
ENV_NAME= "SpectrumAnalyzer"
INSTALL_DIR="${HOME}/${APP_NAME}"
CONDA_DIR="${HOME}/miniforge3"

PIP_PACKAGES=(
    "fastapi>=0.111.0"
    "uvicorn[standard]>=0.29.0"
    "websockets>=12.0"
    "starlette>=0.37.0"
    "httpx>=0.27.0"
)

R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'; B='\033[0;34m'; C='\033[0;36m'
BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${B}[INFO]${NC}  $*"; }
ok()      { echo -e "${G}[  OK]${NC}  $*"; }
warn()    { echo -e "${Y}[WARN]${NC}  $*"; }
die()     { echo -e "${R}[FAIL]${NC}  $*" >&2; exit 1; }
section() { echo -e "\n${BOLD}${C}══  $*  ══${NC}\n"; }
has()     { command -v "$1" &>/dev/null; }

section "SpectrumAnalyzer Linux Installer"
echo "  Bundle directory: ${SCRIPT_DIR}"
echo "  Install target:   ${INSTALL_DIR}"
echo ""

# ── 1. System packages ──────────────────────────────────────────────────────
info "[1/7] Installing system packages..."
if has apt-get; then
    sudo apt-get install -y --no-install-recommends \
        libusb-1.0-0 libusb-1.0-0-dev udev rsync 2>/dev/null \
        && ok "System packages installed" \
        || warn "apt-get partially failed — libusb/udev may need manual install"
else
    warn "apt-get not found — ensure libusb-1.0-0 and udev are installed"
fi

# ── 2. HackRF udev rules ────────────────────────────────────────────────────
info "[2/7] Installing HackRF udev rules..."
RULES="/etc/udev/rules.d/53-hackrf.rules"
if [[ ! -f "$RULES" ]]; then
    sudo tee "$RULES" > /dev/null << 'UDEV'
# HackRF family — generated by SpectrumAnalyzer installer
ATTR{idVendor}=="1d50", ATTR{idProduct}=="604b", SYMLINK+="hackrf-jawbreaker-%k", MODE="660", GROUP="plugdev", TAG+="uaccess"
ATTR{idVendor}=="1d50", ATTR{idProduct}=="6089", SYMLINK+="hackrf-one-%k",        MODE="660", GROUP="plugdev", TAG+="uaccess"
ATTR{idVendor}=="1d50", ATTR{idProduct}=="cc15", SYMLINK+="hackrf-rad1o-%k",      MODE="660", GROUP="plugdev", TAG+="uaccess"
ATTR{idVendor}=="1fc9", ATTR{idProduct}=="000c", SYMLINK+="nxp-dfu-%k",           MODE="660", GROUP="plugdev", TAG+="uaccess"
UDEV
    sudo udevadm control --reload-rules 2>/dev/null || true
    sudo udevadm trigger              2>/dev/null || true
    sudo usermod -aG plugdev "$USER"  2>/dev/null || true
    ok "udev rules installed — re-plug HackRF to take effect"
else
    warn "udev rules already exist, skipping"
fi

# ── 3. Install Miniforge ─────────────────────────────────────────────────────
info "[3/7] Installing Miniforge..."
MF_INSTALLER="$(find "$SCRIPT_DIR" -maxdepth 1 -name 'Miniforge3-*-Linux-*.sh' | head -1)"
[[ -n "$MF_INSTALLER" ]] || die "Miniforge installer not found in bundle"
if [[ ! -d "$CONDA_DIR" ]]; then
    bash "$MF_INSTALLER" -b -p "$CONDA_DIR" -f \
        || die "Miniforge installation failed"
    ok "Miniforge installed: $CONDA_DIR"
else
    warn "Miniforge already present at $CONDA_DIR, skipping"
fi

# ── 4. Unpack conda environment ──────────────────────────────────────────────
info "[4/7] Unpacking conda environment..."
PACKED_ENV="${SCRIPT_DIR}/SpectrumAnalyser_env.tar.gz"
[[ -f "$PACKED_ENV" ]] || die "Packed env not found: $PACKED_ENV"
ENV_DIR="${CONDA_DIR}/envs/${ENV_NAME}"
if [[ ! -d "$ENV_DIR" ]]; then
    mkdir -p "$ENV_DIR"
    info "  Decompressing (2–5 min)..."
    tar -xzf "$PACKED_ENV" -C "$ENV_DIR" || die "tar extraction failed"
    info "  Relinking paths (conda-unpack)..."
    "${ENV_DIR}/bin/conda-unpack" 2>/dev/null \
        && ok "Environment relinked" \
        || warn "conda-unpack not found — relinking skipped"
    ok "Conda environment ready: $ENV_DIR"
else
    warn "Conda environment already exists, skipping"
fi

# ── 5. Install pip packages offline ─────────────────────────────────────────
info "[5/7] Installing pip packages from local wheels..."
WHEEL_DIR="${SCRIPT_DIR}/pip_wheels"
[[ -d "$WHEEL_DIR" ]] || die "pip_wheels directory not found in bundle"
"${ENV_DIR}/bin/pip" install --no-index --find-links "$WHEEL_DIR" \
    "${PIP_PACKAGES[@]}" || die "pip offline install failed"
ok "Pip packages installed"

# ── 6. Deploy application ────────────────────────────────────────────────────
info "[6/7] Deploying application to ${INSTALL_DIR}..."
mkdir -p "$INSTALL_DIR"
if has rsync; then
    rsync -a --exclude='__pycache__/' --exclude='*.pyc' \
        "${SCRIPT_DIR}/app/" "${INSTALL_DIR}/"
else
    cp -r "${SCRIPT_DIR}/app/." "${INSTALL_DIR}/"
    find "$INSTALL_DIR" -type d -name '__pycache__' -exec rm -rf {} + 2>/dev/null || true
fi
ok "Application deployed: $INSTALL_DIR"

# ── 7. Create shortcuts ──────────────────────────────────────────────────────
info "[7/7] Creating shortcuts..."

# Run wrapper
cat > "${INSTALL_DIR}/run_app.sh" << WRAPPER
#!/usr/bin/env bash
export PATH="${ENV_DIR}/bin:\${PATH}"
export CONDA_PREFIX="${ENV_DIR}"
export LD_LIBRARY_PATH="${ENV_DIR}/lib:\${LD_LIBRARY_PATH:-}"
export QT_QPA_PLATFORM_PLUGIN_PATH="${ENV_DIR}/plugins/platforms"
[[ "\${1:-}" == "--headless" ]] && export QT_QPA_PLATFORM=offscreen
cd "${INSTALL_DIR}"
exec "${ENV_DIR}/bin/python" run.py "\$@"
WRAPPER
chmod +x "${INSTALL_DIR}/run_app.sh"

# Terminal command
mkdir -p "${HOME}/.local/bin"
cat > "${HOME}/.local/bin/${APP_NAME}" << LAUNCH
#!/usr/bin/env bash
exec bash "${INSTALL_DIR}/run_app.sh" "\$@"
LAUNCH
chmod +x "${HOME}/.local/bin/${APP_NAME}"

# Add ~/.local/bin to PATH
for RC in "${HOME}/.bashrc" "${HOME}/.profile"; do
    [[ -f "$RC" ]] && ! grep -qF '.local/bin' "$RC" \
        && echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$RC" \
        && ok "PATH updated: $RC"
done
export PATH="${HOME}/.local/bin:${PATH}"

# Desktop .desktop entry
APP_DIR="${HOME}/.local/share/applications"
ICON_DIR="${HOME}/.local/share/icons/hicolor/scalable/apps"
mkdir -p "$APP_DIR" "$ICON_DIR"

cat > "${ICON_DIR}/SpectrumAnalyzer.svg" << 'SVGEOF'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <rect width="64" height="64" rx="10" fill="#0d1117"/>
  <line x1="4" y1="54" x2="60" y2="54" stroke="#21262d" stroke-width="1"/>
  <line x1="4" y1="10" x2="4"  y2="54" stroke="#21262d" stroke-width="1"/>
  <line x1="4" y1="32" x2="60" y2="32" stroke="#21262d" stroke-width="0.6" stroke-dasharray="3,3"/>
  <polyline points="4,50 8,47 12,45 16,42 20,43 23,36 25,26 27,19 29,17 31,14 33,16 35,21 38,31 42,38 46,42 50,45 54,47 60,50"
    stroke="#00e5a0" stroke-width="2.2" fill="none" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="31" cy="14" r="2.8" fill="#ff4c60"/>
</svg>
SVGEOF

cat > "${APP_DIR}/SpectrumAnalyzer.desktop" << DESK
[Desktop Entry]
Version=1.1
Type=Application
Name=SpectrumAnalyzer
GenericName=SDR Spectrum Analyzer
Comment=HackRF One / USRP real-time RF spectrum monitoring
Exec=${HOME}/.local/bin/SpectrumAnalyzer
Icon=SpectrumAnalyzer
Terminal=false
Categories=Science;HamRadio;Engineering;
Keywords=SDR;HackRF;USRP;spectrum;RF;satellite;
StartupNotify=true
DESK
chmod +x "${APP_DIR}/SpectrumAnalyzer.desktop"

# Desktop shortcut
[[ -d "${HOME}/Desktop" ]] && cp "${APP_DIR}/SpectrumAnalyzer.desktop" "${HOME}/Desktop/SpectrumAnalyzer.desktop" \
    && chmod +x "${HOME}/Desktop/SpectrumAnalyzer.desktop" \
    && gio set "${HOME}/Desktop/SpectrumAnalyzer.desktop" metadata::trusted true 2>/dev/null || true

# Systemd user service (headless / Pi)
SVCDIR="${HOME}/.config/systemd/user"
mkdir -p "$SVCDIR"
cat > "${SVCDIR}/SpectrumAnalyzer.service" << SYSD
[Unit]
Description=SpectrumAnalyzer SDR Spectrum Monitor
After=network-online.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_DIR}
Environment="PATH=${ENV_DIR}/bin:/usr/local/bin:/usr/bin:/bin"
Environment="LD_LIBRARY_PATH=${ENV_DIR}/lib"
Environment="QT_QPA_PLATFORM=offscreen"
ExecStart=${ENV_DIR}/bin/python run.py --headless
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
SYSD
systemctl --user daemon-reload 2>/dev/null || true

update-desktop-database "$APP_DIR"   2>/dev/null || true
gtk-update-icon-cache -f -t "${HOME}/.local/share/icons/hicolor" 2>/dev/null || true

ok ""
section "INSTALLATION COMPLETE"
echo -e "  ${G}Terminal (new shell):${NC}       SpectrumAnalyzer"
echo -e "  ${G}Terminal (this shell):${NC}      source ~/.bashrc && SpectrumAnalyzer"
echo -e "  ${G}Headless web mode:${NC}          SpectrumAnalyzer --headless"
echo -e "  ${G}Desktop icon:${NC}               double-click SpectrumAnalyzer"
echo -e "  ${G}Headless autostart on boot:${NC} systemctl --user enable --now SpectrumAnalyzer"
echo -e "  ${G}View service logs:${NC}          journalctl --user -u SpectrumAnalyzer -f"
echo ""
warn "Re-plug the HackRF USB cable so the udev rules take effect."
warn "Open a new terminal before using the 'SpectrumAnalyzer' command."
"""

# ── Windows PowerShell installer ────────────────────────────────────────────
INSTALL_PS1 = r"""
# =============================================================================
#  SpectrumAnalyzer  —  Windows offline installer
#  Generated by SpectrumAnalyzer_prepare.py
#
#  Run from the directory where you unzipped the bundle:
#      Right-click install.ps1 -> "Run with PowerShell"
#      OR open PowerShell in this folder and type:
#          powershell -ExecutionPolicy Bypass -File .\install.ps1
#
#  Requires: PowerShell 5+ and Windows 10/11 (tar.exe built in)
# =============================================================================
#Requires -Version 5.0
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Definition
$AppName    = "SpectrumAnalyzer"
$EnvName    = "SpectrumAnalyzer"
$CondaDir   = "$env:USERPROFILE\miniforge3"
$EnvDir     = "$CondaDir\envs\$EnvName"
$InstallDir = "$env:USERPROFILE\$AppName"

$PipPackages = @(
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.29.0",
    "websockets>=12.0",
    "starlette>=0.37.0",
    "httpx>=0.27.0"
)

function Write-Section($msg) {
    Write-Host "`n$('=' * 60)" -ForegroundColor Cyan
    Write-Host "  $msg" -ForegroundColor Cyan
    Write-Host $('=' * 60) -ForegroundColor Cyan
}
function Write-OK($msg)   { Write-Host "[  OK]  $msg" -ForegroundColor Green }
function Write-Info($msg) { Write-Host "[INFO]  $msg" -ForegroundColor Blue  }
function Write-Warn($msg) { Write-Host "[WARN]  $msg" -ForegroundColor Yellow }
function Write-Fail($msg) { Write-Host "[FAIL]  $msg" -ForegroundColor Red; exit 1 }

Write-Section "SpectrumAnalyzer Windows Installer"
Write-Info "Bundle directory: $ScriptDir"
Write-Info "Install target:   $InstallDir"

# ── 1. Install Miniforge ──────────────────────────────────────────────────────
Write-Info "[1/6] Installing Miniforge..."
$MFInstaller = Get-ChildItem -Path $ScriptDir -Filter "Miniforge3-*-Windows-*.exe" |
               Select-Object -First 1
if (-not $MFInstaller) { Write-Fail "Miniforge installer not found in bundle directory" }

if (Test-Path $CondaDir) {
    Write-Warn "Miniforge already present at $CondaDir — skipping"
} else {
    Write-Info "  Running silent Miniforge install (takes ~2 min)..."
    $proc = Start-Process -FilePath $MFInstaller.FullName `
        -ArgumentList "/S", "/InstallationType=JustMe", "/RegisterPython=0", "/D=$CondaDir" `
        -Wait -PassThru -NoNewWindow
    if ($proc.ExitCode -ne 0) { Write-Fail "Miniforge install exited with code $($proc.ExitCode)" }
    Write-OK "Miniforge installed: $CondaDir"
}

# ── 2. Unpack conda environment ───────────────────────────────────────────────
Write-Info "[2/6] Unpacking conda environment..."
$PackedEnv = Join-Path $ScriptDir "SpectrumAnalyzer_env.tar.gz"
if (-not (Test-Path $PackedEnv)) { Write-Fail "Packed env not found: $PackedEnv" }

if (Test-Path $EnvDir) {
    Write-Warn "Conda environment already exists at $EnvDir — skipping"
} else {
    New-Item -ItemType Directory -Path $EnvDir -Force | Out-Null
    Write-Info "  Decompressing environment (2–5 min)..."
    # tar.exe ships with Windows 10+ at C:\Windows\System32\tar.exe
    $tarExe = "$env:SystemRoot\System32\tar.exe"
    if (-not (Test-Path $tarExe)) { $tarExe = "tar" }
    & $tarExe -xzf $PackedEnv -C $EnvDir
    if ($LASTEXITCODE -ne 0) { Write-Fail "tar extraction failed" }

    Write-Info "  Relinking environment paths (conda-unpack)..."
    $unpackExe = Join-Path $EnvDir "Scripts\conda-unpack.exe"
    if (Test-Path $unpackExe) {
        & $unpackExe
        Write-OK "Environment relinked"
    } else {
        Write-Warn "conda-unpack.exe not found — relinking skipped (may still work)"
    }
    Write-OK "Conda environment ready: $EnvDir"
}

# ── 3. Install pip packages from local wheels ─────────────────────────────────
Write-Info "[3/6] Installing pip packages from local wheels..."
$WheelDir = Join-Path $ScriptDir "pip_wheels"
if (-not (Test-Path $WheelDir)) { Write-Fail "pip_wheels directory not found in bundle" }
$PipExe = Join-Path $EnvDir "Scripts\pip.exe"
& $PipExe install --no-index --find-links $WheelDir $PipPackages
if ($LASTEXITCODE -ne 0) { Write-Fail "pip offline install failed" }
Write-OK "Pip packages installed"

# ── 4. Deploy application ─────────────────────────────────────────────────────
Write-Info "[4/6] Deploying application to $InstallDir..."
New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
$AppSrc = Join-Path $ScriptDir "app"
if (-not (Test-Path $AppSrc)) { Write-Fail "app/ directory not found in bundle" }
Copy-Item -Path "$AppSrc\*" -Destination $InstallDir -Recurse -Force
# Remove __pycache__ directories
Get-ChildItem -Path $InstallDir -Filter "__pycache__" -Recurse -Directory |
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
Write-OK "Application deployed: $InstallDir"

# ── 5. Create launcher batch file ─────────────────────────────────────────────
Write-Info "[5/6] Creating launchers..."

$LauncherBat = Join-Path $InstallDir "run_app.bat"
@"
@echo off
set "CONDA_PREFIX=$EnvDir"
set "PATH=$EnvDir;$EnvDir\Scripts;$EnvDir\Library\bin;%PATH%"
set "QT_QPA_PLATFORM_PLUGIN_PATH=$EnvDir\Library\plugins\platforms"
cd /d "$InstallDir"
if "%1"=="--headless" set "QT_QPA_PLATFORM=offscreen"
"$EnvDir\python.exe" run.py %*
"@ | Set-Content -Path $LauncherBat -Encoding ASCII

# Add env to user PATH (permanent, no admin needed)
$userPath = [Environment]::GetEnvironmentVariable("PATH", "User")
$newEntry = "$EnvDir\Scripts;$EnvDir;$EnvDir\Library\bin"
if ($userPath -notlike "*$EnvDir*") {
    [Environment]::SetEnvironmentVariable("PATH", "$newEntry;$userPath", "User")
    Write-OK "User PATH updated (effective after new terminal)"
}

# ── 6. Create shortcuts ───────────────────────────────────────────────────────
Write-Info "[6/6] Creating desktop and Start Menu shortcuts..."
$WshShell = New-Object -ComObject WScript.Shell

# Desktop shortcut
$DesktopLnk = Join-Path ([Environment]::GetFolderPath("Desktop")) "SpectrumAnalyzer.lnk"
$Shortcut = $WshShell.CreateShortcut($DesktopLnk)
$Shortcut.TargetPath       = "cmd.exe"
$Shortcut.Arguments        = "/c `"$LauncherBat`""
$Shortcut.WorkingDirectory = $InstallDir
$Shortcut.Description      = "SpectrumAnalyzer SDR Spectrum Monitor"
$Shortcut.WindowStyle      = 1
$Shortcut.Save()
Write-OK "Desktop shortcut: $DesktopLnk"

# Start Menu shortcut
$StartMenuDir = Join-Path ([Environment]::GetFolderPath("Programs")) "SpectrumAnalyzer"
New-Item -ItemType Directory -Path $StartMenuDir -Force | Out-Null
$StartLnk = Join-Path $StartMenuDir "SpectrumAnalyzer.lnk"
$Shortcut2 = $WshShell.CreateShortcut($StartLnk)
$Shortcut2.TargetPath       = "cmd.exe"
$Shortcut2.Arguments        = "/c `"$LauncherBat`""
$Shortcut2.WorkingDirectory = $InstallDir
$Shortcut2.Description      = "SpectrumAnalyzer SDR Spectrum Monitor"
$Shortcut2.WindowStyle      = 1
$Shortcut2.Save()
Write-OK "Start Menu shortcut: $StartLnk"

# Headless launcher (runs web server, no GUI window)
$HeadlessLnk = Join-Path $StartMenuDir "SpectrumAnalyzer (Headless Web).lnk"
$Shortcut3 = $WshShell.CreateShortcut($HeadlessLnk)
$Shortcut3.TargetPath       = "cmd.exe"
$Shortcut3.Arguments        = "/c `"$LauncherBat`" --headless"
$Shortcut3.WorkingDirectory = $InstallDir
$Shortcut3.Description      = "SpectrumAnalyzer headless web interface"
$Shortcut3.WindowStyle      = 1
$Shortcut3.Save()
Write-OK "Headless Start Menu entry created"

# ── Summary ───────────────────────────────────────────────────────────────────
Write-Section "INSTALLATION COMPLETE"
Write-Host ""
Write-Host "  Launch options:" -ForegroundColor White
Write-Host "    Desktop shortcut:        double-click SpectrumAnalyzer" -ForegroundColor Green
Write-Host "    Start Menu:              Start > SpectrumAnalyzer" -ForegroundColor Green
Write-Host "    Terminal (new window):   run_app.bat" -ForegroundColor Green
Write-Host "    Headless web mode:       run_app.bat --headless" -ForegroundColor Green
Write-Host ""
Write-Host "  HackRF USB driver:" -ForegroundColor Yellow
Write-Host "    The HackRF requires the WinUSB driver installed via Zadig." -ForegroundColor Yellow
Write-Host "    Zadig download:  https://zadig.akeo.ie  (one-time, needs internet)" -ForegroundColor Yellow
Write-Host "    In Zadig: select 'HackRF One', choose 'WinUSB', click Install." -ForegroundColor Yellow
Write-Host ""
Write-Host "  Verify after install:" -ForegroundColor White
Write-Host "    Open a new terminal then:" -ForegroundColor White
Write-Host "      hackrf_info" -ForegroundColor Cyan
Write-Host "      SoapySDRUtil --find" -ForegroundColor Cyan
Write-Host ""
"""

# ── Windows double-click launcher for install.ps1 ──────────────────────────
INSTALL_BAT = r"""@echo off
:: SpectrumAnalyzer Windows installer launcher
:: Double-click this file to run the PowerShell installer.
echo.
echo  SpectrumAnalyzer Installer
echo  ========================
echo  This will install SpectrumAnalyzer and all dependencies.
echo  A PowerShell window will open to show progress.
echo.
pause

powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0install.ps1"

echo.
echo Installation complete.  Press any key to close.
pause > nul
"""

# ── README bundled inside the zip ──────────────────────────────────────────
def _readme(target_os: str, arch: str) -> str:
    if target_os == "linux":
        install_cmd = "bash install.sh"
        run_cmd     = "SpectrumAnalyzer  (open a new terminal first)"
        headless    = "SpectrumAnalyzer --headless"
    else:
        install_cmd = "double-click install.bat  OR  right-click install.ps1 → Run with PowerShell"
        run_cmd     = "double-click SpectrumAnalyzer on Desktop  OR  run_app.bat"
        headless    = "run_app.bat --headless"

    return textwrap.dedent(f"""\
    SpectrumAnalyzer — Offline Installation Bundle
    ==========================================
    Platform : {target_os} / {arch}
    Built by : SpectrumAnalyzer_prepare.py

    CONTENTS
    --------
    Miniforge3-{target_os}-{arch}.*     Conda/Python installer
    SpectrumAnalyzer_env.tar.gz              Packed Python environment
    pip_wheels/                          FastAPI, uvicorn, websockets, …
    app/                                 SpectrumAnalyzer source code
    install.sh  / install.ps1            Platform installer scripts
    install.bat                          Windows double-click launcher

    INSTALL
    -------
    1. Extract (unzip) this archive to any folder.
    2. Run:  {install_cmd}
    3. Launch: {run_cmd}
       Headless: {headless}

    REQUIREMENTS ON TARGET MACHINE
    --------------------------------
    Linux   : bash, tar, awk  (always present — NO Python or conda needed)
    Windows : PowerShell 5+ and Windows 10 / 11  (tar.exe is built in)

    HACKRF USB DRIVER
    -----------------
    Linux   : udev rules are installed automatically. Re-plug after install.
    Windows : Install WinUSB driver via Zadig (https://zadig.akeo.ie).
              Select "HackRF One" → "WinUSB" → Install Driver.
              This step requires internet or a separate Zadig download.
    """)


# ═══════════════════════════════════════════════════════════════════════════
#  HELPERS
# ═══════════════════════════════════════════════════════════════════════════

def _print(msg: str, colour: str = "") -> None:
    COLOURS = {"red": "\033[0;31m", "green": "\033[0;32m",
               "yellow": "\033[1;33m", "blue": "\033[0;34m",
               "cyan": "\033[0;36m", "bold": "\033[1m"}
    NC = "\033[0m"
    prefix = COLOURS.get(colour, "")
    # Windows cmd doesn't support ANSI unless enabled; strip on Windows
    if sys.platform == "win32":
        print(msg)
    else:
        print(f"{prefix}{msg}{NC}")


def info(msg):    _print(f"[INFO]  {msg}", "blue")
def ok(msg):      _print(f"[  OK]  {msg}", "green")
def warn(msg):    _print(f"[WARN]  {msg}", "yellow")
def section(msg): _print(f"\n══  {msg}  ══\n", "cyan")
def die(msg):     _print(f"[FAIL]  {msg}", "red"); sys.exit(1)


def download(url: str, dest: Path, label: str = "") -> None:
    """Download url → dest with a simple progress indicator."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    label = label or dest.name
    info(f"Downloading {label} …")
    try:
        with urllib.request.urlopen(url, timeout=120) as resp:
            total = int(resp.headers.get("Content-Length", 0))
            downloaded = 0
            with open(dest, "wb") as f:
                while chunk := resp.read(1 << 16):   # 64 KB chunks
                    f.write(chunk)
                    downloaded += len(chunk)
                    if total:
                        pct = downloaded * 100 // total
                        print(f"\r  {pct:3d}%  {downloaded >> 20} MB / {total >> 20} MB",
                              end="", flush=True)
        print()  # newline after progress
        ok(f"Downloaded: {dest.name}  ({dest.stat().st_size >> 20} MB)")
    except urllib.error.URLError as exc:
        die(f"Download failed: {url}\n  {exc}")


def run_cmd(cmd: list, **kwargs) -> subprocess.CompletedProcess:
    """Run a subprocess, raising on failure."""
    return subprocess.run(cmd, check=True, **kwargs)


def _miniforge_url(target_os: str, arch: str) -> tuple[str, str]:
    """Return (url, filename) for the Miniforge installer."""
    v = MINIFORGE_VERSION
    if target_os == "windows":
        name = f"Miniforge3-{v}-Windows-x86_64.exe"
    else:
        name = f"Miniforge3-{v}-Linux-{arch}.sh"
    url = (f"https://github.com/conda-forge/miniforge/releases/download/{v}/{name}")
    return url, name



def _win_build_root() -> Path:
    """
    Return a short, guaranteed-space-free build root on Windows.

    The NSIS installer /D= flag silently fails (exit code 2) when the install
    path contains spaces, or when Python passes it as a quoted shell token.
    We avoid both by keeping all Windows build artefacts under
    %USERPROFILE%\\fa_build — a short path with no spaces.
    """
    return Path(os.environ.get("USERPROFILE", "C:\\")) / "fa_build"


def _ensure_mamba(work: Path, mf_installer: Path, target_os: str) -> Path:
    """
    Install a temporary Miniforge and return the path to the mamba binary.

    Windows notes
    -------------
    The Miniforge .exe is an NSIS installer with two strict rules:
      1. /D= must be the VERY LAST argument on the command line.
      2. The path after /D= must NOT be quoted (even with spaces).
    Python subprocess list-form automatically quotes arguments, triggering
    exit code 2.  We fix this two ways:
      a. shell=True so the command string reaches NSIS verbatim.
      b. tmp_conda lives under %USERPROFILE%\\fa_build\\tmp_conda —
         guaranteed no spaces, regardless of where the project folder is.
    """
    if target_os == "windows":
        # Short, space-free path regardless of where the project lives
        tmp_conda = _win_build_root() / "tmp_conda"
    else:
        tmp_conda = work / "tmp_conda"

    if not tmp_conda.exists():
        info("Bootstrapping temporary Miniforge for package operations...")
        tmp_conda.parent.mkdir(parents=True, exist_ok=True)

        if target_os == "windows":
            # Use shell=True + raw string so Python never quotes the /D= path
            install_cmd = (
                f'"{mf_installer}" /S /InstallationType=JustMe '
                f'/RegisterPython=0 /D={tmp_conda}'
            )
            info(f"  Running: {install_cmd}")
            result = subprocess.run(install_cmd, shell=True)
            if result.returncode not in (0, 3010):  # 3010 = reboot needed (harmless)
                die(
                    f"Miniforge installer failed (exit code {result.returncode}).\n"
                    f"  Install path tried: {tmp_conda}\n"
                    f"  Ensure the path exists and contains no spaces."
                )
        else:
            run_cmd(["bash", str(mf_installer), "-b", "-p", str(tmp_conda), "-f"])

        ok(f"Temporary Miniforge at {tmp_conda}")
    else:
        warn(f"Temporary Miniforge already exists at {tmp_conda}, skipping")

    if target_os == "windows":
        mamba = tmp_conda / "Scripts" / "mamba.exe"
    else:
        mamba = tmp_conda / "bin" / "mamba"

    if not mamba.exists():
        die(
            f"mamba not found at {mamba}\n"
            f"  The Miniforge installation likely failed silently.\n"
            f"  Delete {tmp_conda} and run the script again."
        )

    # Ensure conda-pack is available in the temporary base env
    info("Ensuring conda-pack is in the temporary base environment...")
    run_cmd([str(mamba), "install", "-y", "-n", "base",
             "-c", "conda-forge", "conda-pack", "--quiet"])
    return mamba


# ═══════════════════════════════════════════════════════════════════════════
#  MAIN PREPARE LOGIC
# ═══════════════════════════════════════════════════════════════════════════


# ── Unicode → ASCII sanitiser for embedded script templates ─────────────────
# PowerShell and bash both fail on box-drawing / dash Unicode characters when
# the file encoding is not declared.  Replace every non-ASCII char with a safe
# ASCII equivalent before writing templates into the ZIP.
_UNICODE_MAP = str.maketrans({
    '\u2014': '-',   # em dash        —
    '\u2013': '-',   # en dash        -
    '\u2012': '-',   # figure dash
    '\u2010': '-',   # hyphen
    '\u2500': '-',   # box light horiz ─
    '\u2501': '-',   # box heavy horiz
    '\u2550': '=',   # box double horiz ═
    '\u2502': '|',   # box light vert
    '\u2551': '|',   # box double vert
    '\u2018': "'",   # left single quote
    '\u2019': "'",   # right single quote
    '\u201c': '"',   # left double quote
    '\u201d': '"',   # right double quote
    '\u2026': '...', # ellipsis
    '\u00e2': '',    # garbage from bad re-encode
})

def _ascii(text: str) -> str:
    """Replace every known Unicode decoration with plain ASCII."""
    text = text.translate(_UNICODE_MAP)
    # Catch anything else above 0x7F with a fallback
    return text.encode('ascii', errors='replace').decode('ascii').replace('?', '-')

# UTF-8 BOM — tells PowerShell the file is UTF-8, preventing misread of any
# remaining special bytes.
_UTF8_BOM = '\ufeff'

def cmd_prepare(args) -> None:
    target_os = "windows" if sys.platform == "win32" else "linux"
    arch      = args.arch
    work      = Path(args.workdir).resolve()
    out_zip   = Path(args.outdir).resolve() / f"SpectrumAnalyzer_bundle_{target_os}_{arch}.zip"

    section(f"PREPARE — building offline bundle for {target_os}/{arch}")
    info(f"Build workspace : {work}")
    info(f"Output archive  : {out_zip}")

    if args.clean and work.exists():
        warn(f"--clean: removing {work}")
        shutil.rmtree(work)

    work.mkdir(parents=True, exist_ok=True)
    (work / "pip_wheels").mkdir(exist_ok=True)

    # ── Step 1: Download Miniforge installer ─────────────────────────────────
    section("Step 1/5 — Downloading Miniforge installer")
    url, mf_name = _miniforge_url(target_os, arch)
    mf_path = work / mf_name
    if not mf_path.exists():
        download(url, mf_path, mf_name)
    else:
        warn(f"Already present: {mf_name}")

    # ── Step 2: Bootstrap temporary conda + create environment ───────────────
    section("Step 2/5 — Creating conda environment")
    mamba = _ensure_mamba(work, mf_path, target_os)

    # On Windows, keep tmp_env under the space-free fa_build root
    if target_os == "windows":
        tmp_env = _win_build_root() / "tmp_env"
    else:
        tmp_env = work / "tmp_env"
    if tmp_env.exists():
        warn("Removing existing tmp_env for clean build...")
        shutil.rmtree(tmp_env)

    info("Creating conda environment (resolving all packages — 5–15 min)…")
    run_cmd([str(mamba), "create", "-y",
             "--prefix", str(tmp_env),
             *CONDA_CHANNELS,
             *CONDA_PACKAGES])
    ok("Conda environment created")

    # ── Step 3: Download pip wheels ──────────────────────────────────────────
    section("Step 3/5 — Downloading pip wheels")
    if target_os == "windows":
        pip_exe = tmp_env / "Scripts" / "pip.exe"
    else:
        pip_exe = tmp_env / "bin" / "pip"

    run_cmd([str(pip_exe), "download",
             "--dest", str(work / "pip_wheels"),
             "--prefer-binary",
             *PIP_PACKAGES])
    ok("Pip wheels downloaded")

    # ── Step 4: conda-pack the environment ───────────────────────────────────
    section("Step 4/5 — Packing conda environment (3–10 min)")
    # Keep the packed env in the same space-free directory as tmp_env
    if target_os == "windows":
        packed_env = _win_build_root() / "SpectrumAnalyzer_env.tar.gz"
    else:
        packed_env = work / "SpectrumAnalyzer_env.tar.gz"
    if target_os == "windows":
        conda_pack_exe = _win_build_root() / "tmp_conda" / "Scripts" / "conda-pack.exe"
    else:
        conda_pack_exe = work / "tmp_conda" / "bin" / "conda-pack"

    run_cmd([str(conda_pack_exe),
             "--prefix", str(tmp_env),
             "--output", str(packed_env),
             "--force"])
    ok(f"Environment packed: {packed_env.stat().st_size >> 20} MB")

    # ── Step 5: Copy app source ───────────────────────────────────────────────
    section("Step 5/5 — Copying application source")
    app_dest = work / "app"
    if app_dest.exists():
        shutil.rmtree(app_dest)
    # Exclude files that should not be in the bundle
    EXCLUDE = {
        ".git", "__pycache__", ".pytest_cache",
        "*.pyc", "*.pyo", "*.egg-info",
        args.workdir,                    # don't bundle the build workspace
        out_zip.name,
    }

    def _ignore(directory, contents):
        ignored = set()
        for item in contents:
            if item in EXCLUDE:
                ignored.add(item)
            if any(item.endswith(e.lstrip("*")) for e in EXCLUDE if e.startswith("*")):
                ignored.add(item)
        return ignored

    shutil.copytree(APP_SOURCE_DIR, app_dest, ignore=_ignore,
                    ignore_dangling_symlinks=True)
    # Remove this prepare script from the app copy
    for f in app_dest.glob("SpectrumAnalyzer_prepare.py"):
        f.unlink()
    ok(f"Application source copied ({sum(1 for _ in app_dest.rglob('*'))} files)")

    # ── Assemble the ZIP ──────────────────────────────────────────────────────
    section("Assembling bundle ZIP")
    info(f"Output: {out_zip}")

    out_zip.parent.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED,
                         compresslevel=6) as zf:

        def _add(src: Path, arc_name: str) -> None:
            zf.write(src, arc_name)

        def _add_str(content: str, arc_name: str, mode: int = 0o644) -> None:
            info_obj = zipfile.ZipInfo(arc_name)
            info_obj.external_attr = (mode << 16)
            info_obj.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(info_obj, content)

        # Miniforge installer
        _add(mf_path, mf_name)
        info(f"  + {mf_name}")

        # Packed conda environment
        _add(packed_env, "SpectrumAnalyzer_env.tar.gz")
        info("  + SpectrumAnalyzer_env.tar.gz")

        # Pip wheels
        wheel_count = 0
        for whl in (work / "pip_wheels").iterdir():
            _add(whl, f"pip_wheels/{whl.name}")
            wheel_count += 1
        info(f"  + pip_wheels/  ({wheel_count} wheels)")

        # Application source
        file_count = 0
        for src in app_dest.rglob("*"):
            if src.is_file():
                arc = "app/" + str(src.relative_to(app_dest)).replace(os.sep, "/")
                _add(src, arc)
                file_count += 1
        info(f"  + app/  ({file_count} files)")

        # Installer scripts
        _add_str(_ascii(INSTALL_SH),  "install.sh",  mode=0o755)
        _add_str(_UTF8_BOM + _ascii(INSTALL_PS1), "install.ps1", mode=0o644)
        _add_str(_ascii(INSTALL_BAT), "install.bat", mode=0o644)
        _add_str(_readme(target_os, arch), "README.txt", mode=0o644)
        info("  + install.sh / install.ps1 / install.bat / README.txt")

    size_mb = out_zip.stat().st_size >> 20
    ok("")
    ok("=" * 62)
    ok(f" Bundle ready: {out_zip.name}")
    ok(f" Size:         {size_mb} MB")
    ok("=" * 62)

    print()
    info("Transfer to the offline machine (USB drive, scp, etc.):")
    info(f"  {out_zip.name}")
    print()
    info("On the offline machine:")
    if target_os == "linux":
        info(f"  unzip {out_zip.name}")
        info("  cd SpectrumAnalyzer_bundle")
        info("  bash install.sh")
        print()
        info("After install (new terminal):")
        info("  SpectrumAnalyzer               # GUI")
        info("  SpectrumAnalyzer --headless    # web-only")
    else:
        info(f"  Unzip {out_zip.name}")
        info("  Double-click install.bat")
        info("     — or —")
        info("  Right-click install.ps1 → 'Run with PowerShell'")


# ═══════════════════════════════════════════════════════════════════════════
#  STATUS  (verify a previous installation on THIS machine)
# ═══════════════════════════════════════════════════════════════════════════

def cmd_status() -> None:
    section("SpectrumAnalyzer — Installation Status")
    is_win = sys.platform == "win32"
    home   = Path.home()

    if is_win:
        conda_dir   = home / "miniforge3"
        env_dir     = conda_dir / "envs" / ENV_NAME
        install_dir = home / APP_NAME
        launcher    = install_dir / "run_app.bat"
    else:
        conda_dir   = home / "miniforge3"
        env_dir     = conda_dir / "envs" / ENV_NAME
        install_dir = home / APP_NAME
        launcher    = home / ".local" / "bin" / APP_NAME

    G = "\033[0;32m✓\033[0m"
    B = "\033[0;31m✗\033[0m"

    def chk(label, path):
        mark = G if Path(path).exists() else B
        print(f"  {mark}  {label:40s} {path}")

    chk("Miniforge",             conda_dir)
    chk(f"Conda env '{ENV_NAME}'", env_dir)
    chk("Application (run.py)", install_dir / "run.py")
    chk("Launcher",              launcher)

    python = env_dir / ("python.exe" if is_win else "bin/python")
    if python.exists():
        print()
        print("Python packages:")
        packages = [
            ("numpy",      "numpy"),
            ("scipy",      "scipy"),
            ("PyQt6",      "PyQt6.QtCore"),
            ("pyqtgraph",  "pyqtgraph"),
            ("SoapySDR",   "SoapySDR"),
            ("fastapi",    "fastapi"),
            ("uvicorn",    "uvicorn"),
            ("websockets", "websockets"),
        ]
        check_code = (
            "import importlib, sys\n"
            "pkgs=" + repr(packages) + "\n"
            "for label, mod in pkgs:\n"
            "    try:\n"
            "        m=importlib.import_module(mod)\n"
            "        print(f'  \\033[0;32m✓\\033[0m  {label:<18} {getattr(m,\"__version__\",\"ok\")}')\n"
            "    except ImportError:\n"
            "        print(f'  \\033[0;31m✗\\033[0m  {label:<18} NOT FOUND')\n"
        )
        subprocess.run([str(python), "-c", check_code])
    else:
        warn("Python not found in conda env — run install first")


# ═══════════════════════════════════════════════════════════════════════════
#  ENTRY POINT
# ═══════════════════════════════════════════════════════════════════════════

def main() -> None:
    host_os   = "windows" if sys.platform == "win32" else "linux"
    host_arch = "x86_64" if platform.machine() in ("x86_64", "AMD64") else "aarch64"

    parser = argparse.ArgumentParser(
        prog="SpectrumAnalyzer_prepare.py",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=textwrap.dedent("""\
            Build an offline installer bundle for SpectrumAnalyzer.

            Run on an internet-connected machine.  Generates a ZIP that
            installs everything on an offline target with no pre-installed
            Python, conda, or internet access.

            NOTE: Build on the SAME platform as the target machine.
              Linux x86_64 machine  → bundle for Linux x86_64 server/desktop
              Linux aarch64 machine → bundle for Raspberry Pi 4/5
              Windows machine       → bundle for Windows
        """),
        epilog=textwrap.dedent("""\
            Examples:
              python SpectrumAnalyzer_prepare.py
              python SpectrumAnalyzer_prepare.py --arch aarch64
              python SpectrumAnalyzer_prepare.py --clean --outdir /mnt/usb

            On offline Linux target:
              unzip SpectrumAnalyzer_bundle_linux_x86_64.zip
              bash install.sh

            On offline Windows target:
              Unzip → double-click install.bat
        """),
    )
    sub = parser.add_subparsers(dest="command")

    p_prep = sub.add_parser("prepare", help="Download all deps and build bundle zip (default)")
    p_prep.add_argument("--arch",    default=host_arch,
                        choices=["x86_64", "aarch64"],
                        help=f"Target CPU architecture (default: {host_arch})")
    p_prep.add_argument("--outdir",  default=".", metavar="DIR",
                        help="Where to write the bundle zip (default: current dir)")
    p_prep.add_argument("--workdir", default=f".SpectrumAnalyzer_build",
                        metavar="DIR", help="Build workspace directory")
    p_prep.add_argument("--clean",   action="store_true",
                        help="Remove the build workspace before starting")

    sub.add_parser("status", help="Verify an existing installation on this machine")

    args = parser.parse_args()

    # Default to 'prepare' when no subcommand given
    if args.command is None:
        # Re-parse with prepare defaults
        args = parser.parse_args(["prepare"])

    if args.command == "prepare":
        # Validate Python version
        if sys.version_info < (3, 7):
            die("Python 3.7 or newer is required.")
        # Validate required tools
        missing = []
        if host_os == "linux":
            for tool in ("bash", "tar", "curl"):
                if not shutil.which(tool):
                    missing.append(tool)
        if missing:
            die(f"Required tools not found: {', '.join(missing)}\n"
                f"  Install with: sudo apt-get install {' '.join(missing)}")
        cmd_prepare(args)

    elif args.command == "status":
        cmd_status()


if __name__ == "__main__":
    main()  