#!/usr/bin/env python3
"""
spectrum_analyzer_prepare.py
=======================
Single-file bundle builder.  Run ONCE on any internet-connected machine.
Produces a ZIP that installs Spectrum Analyzer on a fully offline machine with
NO pre-installed Python, conda, or internet access on the target.

Requirements (build machine only):
    Python 3.7+  --  standard library only, no pip installs needed

Usage:
    python spectrum_analyzer_prepare.py
    python spectrum_analyzer_prepare.py --arch aarch64    # for Raspberry Pi 4/5
    python spectrum_analyzer_prepare.py --clean           # fresh build

What it downloads:
    * Miniforge3 installer  (.sh on Linux, .exe on Windows)
    * All conda packages    (SoapySDR, HackRF driver, PyQt6, scipy, ...)
    * All pip wheels        (FastAPI, uvicorn, websockets, ...)
    * Your application source code

Output:
    spectrum_analyzer_bundle_linux_x86_64.zip   (built on Linux)
    spectrum_analyzer_bundle_linux_aarch64.zip  (built on Linux, --arch aarch64)
    spectrum_analyzer_bundle_windows_x86_64.zip (built on Windows)

On the offline target machine:
    Linux   ->  unzip spectrum_analyzer_bundle_*.zip  &&  bash install.sh
    Windows ->  Unzip  ->  double-click install.bat
                       OR right-click install.ps1 -> "Run with PowerShell"

NOTE: The bundle is platform-specific because conda environments contain
compiled native code.  Build on Linux to deploy on Linux/Pi; build on
Windows to deploy on Windows.
"""

# --- stdlib imports --------------------------------------------------------
import argparse
import os
import platform
import shutil
import stat
import subprocess
import sys
import textwrap
import urllib.request
import urllib.error
import zipfile
from pathlib import Path

# ===========================================================================
#  CONFIGURATION  --  edit only this section
# ===========================================================================

APP_NAME          = "spectrum_analyzer"
ENV_NAME          = "spectrum_analyzer"
MINIFORGE_VERSION = "24.3.0-0"

# Channels: ryanvolz carries SoapySDR and HackRF/USRP native modules
CONDA_CHANNELS = ["-c", "conda-forge", "-c", "ryanvolz", "--override-channels"]

CONDA_PACKAGES = [
    "python=3.11",                   # pinned: 3.14 is pre-release, avoid wheel gaps
    "numpy>=1.24",
    "scipy>=1.11",
    "pyqt6>=6.5",
    "pyqtgraph>=0.13",
    "matplotlib",                    # legacy plot support
    "soapysdr>=0.8",
    "soapysdr-module-hackrf",
    "hackrf",
    "soapysdr-module-uhd",
    "uhd",                           # USRP X300 native driver + firmware tools
    "soapysdr-module-plutosdr",      # PlutoSDR (ADALM-PLUTO) support
    "libiio",                        # required by PlutoSDR SoapySDR module
    "conda-pack",                    # must stay -- target needs conda-unpack
]

# Pure-Python wheels for the FastAPI / WebSocket web layer
PIP_PACKAGES = [
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.29.0",
    "websockets>=12.0",
    "starlette>=0.37.0",
    "httpx>=0.27.0",
]

# Where the app source lives relative to THIS script
APP_SOURCE_DIR = Path(__file__).parent

# ===========================================================================
#  EMBEDDED INSTALLER TEMPLATES
#  These strings are written into the bundle zip as install.sh / install.ps1
# ===========================================================================

# -- Linux installer (bash, no dependencies needed on target) ----------------
INSTALL_SH = r"""#!/usr/bin/env bash
# =============================================================================
#  Spectrum Analyzer  --  Linux offline installer
#  Generated by spectrum_analyzer_prepare.py
#
#  Run from the directory where you unzipped the bundle:
#      bash install.sh
#
#  Requires ONLY: bash, tar, awk, find   (all standard on every Linux)
# =============================================================================
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_NAME="spectrum_analyzer"
ENV_NAME="spectrum_analyzer"
INSTALL_DIR="${HOME}/${APP_NAME}"
CONDA_DIR="${HOME}/miniforge3"

PIP_PACKAGES=(
    "fastapi>=0.111.0"
    "uvicorn[standard]>=0.29.0"
    "websockets>=12.0"
    "starlette>=0.37.0"
    "httpx>=0.27.0"
)

R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'; B='\033[0;34m'; C='\033[0;36m'
BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${B}[INFO]${NC}  $*"; }
ok()      { echo -e "${G}[  OK]${NC}  $*"; }
warn()    { echo -e "${Y}[WARN]${NC}  $*"; }
die()     { echo -e "${R}[FAIL]${NC}  $*" >&2; exit 1; }
section() { echo -e "\n${BOLD}${C}==  $*  ==${NC}\n"; }
has()     { command -v "$1" &>/dev/null; }

section "Spectrum Analyzer Linux Installer"
echo "  Bundle directory: ${SCRIPT_DIR}"
echo "  Install target:   ${INSTALL_DIR}"
echo ""

# -- 1. System packages ------------------------------------------------------
info "[1/7] Installing system packages..."
if has apt-get; then
    sudo apt-get install -y --no-install-recommends \
        libusb-1.0-0 libusb-1.0-0-dev udev rsync 2>/dev/null \
        && ok "System packages installed" \
        || warn "apt-get partially failed -- libusb/udev may need manual install"
else
    warn "apt-get not found -- ensure libusb-1.0-0 and udev are installed"
fi

# -- 2. HackRF udev rules ----------------------------------------------------
info "[2/7] Installing HackRF udev rules..."
RULES="/etc/udev/rules.d/53-hackrf.rules"
if [[ ! -f "$RULES" ]]; then
    sudo tee "$RULES" > /dev/null << 'UDEV'
# HackRF family -- generated by spectrum_analyzer installer
ATTR{idVendor}=="1d50", ATTR{idProduct}=="604b", SYMLINK+="hackrf-jawbreaker-%k", MODE="660", GROUP="plugdev", TAG+="uaccess"
ATTR{idVendor}=="1d50", ATTR{idProduct}=="6089", SYMLINK+="hackrf-one-%k",        MODE="660", GROUP="plugdev", TAG+="uaccess"
ATTR{idVendor}=="1d50", ATTR{idProduct}=="cc15", SYMLINK+="hackrf-rad1o-%k",      MODE="660", GROUP="plugdev", TAG+="uaccess"
ATTR{idVendor}=="1fc9", ATTR{idProduct}=="000c", SYMLINK+="nxp-dfu-%k",           MODE="660", GROUP="plugdev", TAG+="uaccess"
UDEV
    sudo udevadm control --reload-rules 2>/dev/null || true
    sudo udevadm trigger              2>/dev/null || true
    sudo usermod -aG plugdev "$USER"  2>/dev/null || true
    ok "udev rules installed -- re-plug HackRF to take effect"
else
    warn "udev rules already exist, skipping"
fi

# -- 3. Install Miniforge -----------------------------------------------------
info "[3/7] Installing Miniforge..."
MF_INSTALLER="$(find "$SCRIPT_DIR" -maxdepth 1 -name 'Miniforge3-*-Linux-*.sh' | head -1)"
[[ -n "$MF_INSTALLER" ]] || die "Miniforge installer not found in bundle"
if [[ ! -d "$CONDA_DIR" ]]; then
    bash "$MF_INSTALLER" -b -p "$CONDA_DIR" -f \
        || die "Miniforge installation failed"
    ok "Miniforge installed: $CONDA_DIR"
else
    warn "Miniforge already present at $CONDA_DIR, skipping"
fi

# -- 4. Unpack conda environment ----------------------------------------------
info "[4/7] Unpacking conda environment..."
PACKED_ENV="${SCRIPT_DIR}/spectrum_analyzer_env.tar.gz"
[[ -f "$PACKED_ENV" ]] || die "Packed env not found: $PACKED_ENV"
ENV_DIR="${CONDA_DIR}/envs/${ENV_NAME}"
if [[ ! -d "$ENV_DIR" ]]; then
    mkdir -p "$ENV_DIR"
    info "  Decompressing (2-5 min)..."
    tar -xzf "$PACKED_ENV" -C "$ENV_DIR" || die "tar extraction failed"
    info "  Relinking paths (conda-unpack)..."
    "${ENV_DIR}/bin/conda-unpack" 2>/dev/null \
        && ok "Environment relinked" \
        || warn "conda-unpack not found -- relinking skipped"
    ok "Conda environment ready: $ENV_DIR"
else
    warn "Conda environment already exists, skipping"
fi

# -- 5. Install pip packages offline -----------------------------------------
info "[5/7] Installing pip packages from local wheels..."
WHEEL_DIR="${SCRIPT_DIR}/pip_wheels"
[[ -d "$WHEEL_DIR" ]] || die "pip_wheels directory not found in bundle"
"${ENV_DIR}/bin/pip" install --no-index --find-links "$WHEEL_DIR" \
    "${PIP_PACKAGES[@]}" || die "pip offline install failed"
ok "Pip packages installed"

# -- 6. Deploy application ----------------------------------------------------
info "[6/7] Deploying application to ${INSTALL_DIR}..."
mkdir -p "$INSTALL_DIR"
if has rsync; then
    rsync -a --exclude='__pycache__/' --exclude='*.pyc' \
        "${SCRIPT_DIR}/app/" "${INSTALL_DIR}/"
else
    cp -r "${SCRIPT_DIR}/app/." "${INSTALL_DIR}/"
    find "$INSTALL_DIR" -type d -name '__pycache__' -exec rm -rf {} + 2>/dev/null || true
fi
ok "Application deployed: $INSTALL_DIR"

# -- 7. Create shortcuts ------------------------------------------------------
info "[7/7] Creating shortcuts..."

# GUI run wrapper
cat > "${INSTALL_DIR}/run_app.sh" << WRAPPER
#!/usr/bin/env bash
export PATH="${ENV_DIR}/bin:\${PATH}"
export CONDA_PREFIX="${ENV_DIR}"
export LD_LIBRARY_PATH="${ENV_DIR}/lib:\${LD_LIBRARY_PATH:-}"
export QT_QPA_PLATFORM_PLUGIN_PATH="${ENV_DIR}/plugins/platforms"
cd "${INSTALL_DIR}"
exec "${ENV_DIR}/bin/python" run.py "\$@"
WRAPPER
chmod +x "${INSTALL_DIR}/run_app.sh"

# Web launcher: starts server silently + opens browser automatically
# How it works:
#   1. Server starts in the background
#   2. Script polls http://localhost:8000 until it responds (max 60s)
#   3. Default browser opens automatically
#   4. Script waits for server process (Ctrl+C or terminal close stops server)
cat > "${INSTALL_DIR}/run_web.sh" << 'WEBWRAP'
#!/usr/bin/env bash
export PATH="__ENV_DIR__/bin:${PATH}"
export CONDA_PREFIX="__ENV_DIR__"
export LD_LIBRARY_PATH="__ENV_DIR__/lib:${LD_LIBRARY_PATH:-}"
export QT_QPA_PLATFORM=offscreen

cd "__INSTALL_DIR__"

echo ""
echo "  ================================================"
echo "   Spectrum Analyzer -- Web Interface"
echo "  ================================================"
echo "   Starting server at http://localhost:8000"
echo "   Browser will open automatically when ready."
echo "   Press Ctrl+C to stop."
echo "  ================================================"
echo ""

# Start server in background, capture PID
"__ENV_DIR__/bin/python" run.py --headless &
SERVER_PID=$!

# Poll until server responds (max 60 seconds)
for i in $(seq 1 60); do
    if curl -sf http://localhost:8000 > /dev/null 2>&1 ||        wget -q --spider http://localhost:8000 > /dev/null 2>&1; then
        break
    fi
    sleep 1
done

# Open browser
echo "  Server ready. Opening browser..."
if command -v xdg-open  &>/dev/null; then xdg-open  http://localhost:8000
elif command -v firefox  &>/dev/null; then firefox   http://localhost:8000 &
elif command -v chromium &>/dev/null; then chromium  http://localhost:8000 &
elif command -v google-chrome &>/dev/null; then google-chrome http://localhost:8000 &
else
    echo "  Could not detect a browser. Open: http://localhost:8000"
fi

echo "  Running. Close this terminal or press Ctrl+C to stop."
wait $SERVER_PID
WEBWRAP

# Replace placeholder paths with real values
sed -i "s|__ENV_DIR__|${ENV_DIR}|g"     "${INSTALL_DIR}/run_web.sh"
sed -i "s|__INSTALL_DIR__|${INSTALL_DIR}|g" "${INSTALL_DIR}/run_web.sh"
chmod +x "${INSTALL_DIR}/run_web.sh"

ok "GUI launcher:  run_app.sh"
ok "Web launcher:  run_web.sh  (auto-opens browser)"

# Terminal command
mkdir -p "${HOME}/.local/bin"
cat > "${HOME}/.local/bin/${APP_NAME}" << LAUNCH
#!/usr/bin/env bash
exec bash "${INSTALL_DIR}/run_app.sh" "\$@"
LAUNCH
chmod +x "${HOME}/.local/bin/${APP_NAME}"

# Add ~/.local/bin to PATH
for RC in "${HOME}/.bashrc" "${HOME}/.profile"; do
    [[ -f "$RC" ]] && ! grep -qF '.local/bin' "$RC" \
        && echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$RC" \
        && ok "PATH updated: $RC"
done
export PATH="${HOME}/.local/bin:${PATH}"

# Desktop .desktop entry
APP_DIR="${HOME}/.local/share/applications"
ICON_DIR="${HOME}/.local/share/icons/hicolor/scalable/apps"
mkdir -p "$APP_DIR" "$ICON_DIR"

cat > "${ICON_DIR}/spectrum_analyzer.svg" << 'SVGEOF'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <rect width="64" height="64" rx="10" fill="#0d1117"/>
  <line x1="4" y1="54" x2="60" y2="54" stroke="#21262d" stroke-width="1"/>
  <line x1="4" y1="10" x2="4"  y2="54" stroke="#21262d" stroke-width="1"/>
  <line x1="4" y1="32" x2="60" y2="32" stroke="#21262d" stroke-width="0.6" stroke-dasharray="3,3"/>
  <polyline points="4,50 8,47 12,45 16,42 20,43 23,36 25,26 27,19 29,17 31,14 33,16 35,21 38,31 42,38 46,42 50,45 54,47 60,50"
    stroke="#00e5a0" stroke-width="2.2" fill="none" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="31" cy="14" r="2.8" fill="#ff4c60"/>
</svg>
SVGEOF

# GUI .desktop entry
cat > "${APP_DIR}/spectrum_analyzer.desktop" << DESK
[Desktop Entry]
Version=1.1
Type=Application
Name=Spectrum Analyzer
GenericName=SDR Spectrum Analyzer
Comment=HackRF One / USRP real-time RF spectrum monitoring
Exec=${HOME}/.local/bin/spectrum_analyzer
Icon=spectrum_analyzer
Terminal=false
Categories=Science;HamRadio;Engineering;
Keywords=SDR;HackRF;USRP;spectrum;RF;satellite;
StartupNotify=true
DESK
chmod +x "${APP_DIR}/spectrum_analyzer.desktop"

# Web .desktop entry (opens browser, runs like a web app)
cat > "${APP_DIR}/spectrum_analyzer_web.desktop" << WEBDESK
[Desktop Entry]
Version=1.1
Type=Application
Name=Spectrum Analyzer (Web)
GenericName=SDR Web Interface
Comment=Start Spectrum Analyzer web server and open in browser
Exec=${INSTALL_DIR}/run_web.sh
Icon=spectrum_analyzer
Terminal=true
Categories=Science;HamRadio;Engineering;
Keywords=SDR;HackRF;USRP;spectrum;web;
StartupNotify=true
WEBDESK
chmod +x "${APP_DIR}/spectrum_analyzer_web.desktop"

# Desktop shortcuts
if [[ -d "${HOME}/Desktop" ]]; then
    cp "${APP_DIR}/spectrum_analyzer.desktop" "${HOME}/Desktop/Spectrum Analyzer.desktop"
    cp "${APP_DIR}/spectrum_analyzer_web.desktop" "${HOME}/Desktop/Spectrum Analyzer (Web).desktop"
    chmod +x "${HOME}/Desktop/Spectrum Analyzer.desktop"
    chmod +x "${HOME}/Desktop/Spectrum Analyzer (Web).desktop"
    gio set "${HOME}/Desktop/Spectrum Analyzer.desktop" metadata::trusted true 2>/dev/null || true
    gio set "${HOME}/Desktop/Spectrum Analyzer (Web).desktop" metadata::trusted true 2>/dev/null || true
    ok "Desktop shortcuts created (GUI + Web)"
fi

# Systemd user service (headless / Pi)
SVCDIR="${HOME}/.config/systemd/user"
mkdir -p "$SVCDIR"
cat > "${SVCDIR}/spectrum_analyzer.service" << SYSD
[Unit]
Description=Spectrum Analyzer SDR Spectrum Monitor
After=network-online.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_DIR}
Environment="PATH=${ENV_DIR}/bin:/usr/local/bin:/usr/bin:/bin"
Environment="LD_LIBRARY_PATH=${ENV_DIR}/lib"
Environment="QT_QPA_PLATFORM=offscreen"
ExecStart=${ENV_DIR}/bin/python run.py --headless
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
SYSD
systemctl --user daemon-reload 2>/dev/null || true

update-desktop-database "$APP_DIR"   2>/dev/null || true
gtk-update-icon-cache -f -t "${HOME}/.local/share/icons/hicolor" 2>/dev/null || true

ok ""
section "INSTALLATION COMPLETE"
echo -e "  ${G}GUI app:${NC}                    double-click  Spectrum Analyzer"
echo -e "  ${G}Web interface:${NC}              double-click  Spectrum Analyzer (Web)"
echo -e "                              -> server starts, browser opens automatically"
echo -e "  ${G}Terminal (GUI):${NC}            spectrum_analyzer"
echo -e "  ${G}Terminal (Web):${NC}            bash ~/spectrum_analyzer/run_web.sh"
echo -e "  ${G}Headless autostart on boot:${NC} systemctl --user enable --now spectrum_analyzer"
echo -e "  ${G}View service logs:${NC}          journalctl --user -u spectrum_analyzer -f"
echo ""
warn "Re-plug the HackRF USB cable so the udev rules take effect."
warn "Open a new terminal before using the 'spectrum_analyzer' command."
"""

# -- Windows PowerShell installer --------------------------------------------
INSTALL_PS1 = r"""
# =============================================================================
#  Spectrum Analyzer  --  Windows offline installer
#  Generated by spectrum_analyzer_prepare.py
#
#  Run from the directory where you unzipped the bundle:
#      Right-click install.ps1 -> "Run with PowerShell"
#      OR open PowerShell in this folder and type:
#          powershell -ExecutionPolicy Bypass -File .\install.ps1
#
#  Requires: PowerShell 5+ and Windows 10/11 (tar.exe built in)
# =============================================================================
#Requires -Version 5.0
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Definition
$ScriptDir  = $ScriptDir.TrimEnd("\")
$AppName    = "spectrum_analyzer"
$EnvName    = "spectrum_analyzer"
$CondaDir   = "$env:USERPROFILE\miniforge3"
$EnvDir     = "$CondaDir\envs\$EnvName"
$InstallDir = "$env:USERPROFILE\$AppName"

$PipPackages = @(
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.29.0",
    "websockets>=12.0",
    "starlette>=0.37.0",
    "httpx>=0.27.0"
)

function Write-Section($msg) {
    Write-Host "`n$('=' * 60)" -ForegroundColor Cyan
    Write-Host "  $msg" -ForegroundColor Cyan
    Write-Host $('=' * 60) -ForegroundColor Cyan
}
function Write-OK($msg)   { Write-Host "[  OK]  $msg" -ForegroundColor Green }
function Write-Info($msg) { Write-Host "[INFO]  $msg" -ForegroundColor Blue  }
function Write-Warn($msg) { Write-Host "[WARN]  $msg" -ForegroundColor Yellow }
function Write-Fail($msg) { Write-Host "[FAIL]  $msg" -ForegroundColor Red; exit 1 }

Write-Section "Spectrum Analyzer Windows Installer"

# -- Auto-elevate to Administrator ─────────────────────────────────────────────
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "Requesting Administrator privileges..." -ForegroundColor Yellow
    $argList = "-NoProfile -ExecutionPolicy Bypass -File `"$($MyInvocation.MyCommand.Definition)`""
    Start-Process PowerShell -Verb RunAs -ArgumentList $argList
    exit
}
Write-Info "Bundle directory: $ScriptDir"
Write-Info "Install target:   $InstallDir"

# -- [1/6] Install Miniforge ---------------------------------------------------
Write-Info "[1/6] Installing Miniforge..."
$MFInstaller = Get-ChildItem -Path $ScriptDir -Filter "Miniforge3-*-Windows-*.exe" |
               Select-Object -First 1
if (-not $MFInstaller) { Write-Fail "Miniforge installer not found in bundle directory" }

if (Test-Path $CondaDir) {
    Write-Warn "Miniforge already present at $CondaDir -- skipping"
} else {
    Write-Info "  Running silent Miniforge install (takes ~2 min)..."
    $proc = Start-Process -FilePath $MFInstaller.FullName `
        -ArgumentList "/S", "/InstallationType=JustMe", "/RegisterPython=0", "/D=$CondaDir" `
        -Wait -PassThru -NoNewWindow
    if ($proc.ExitCode -ne 0) { Write-Fail "Miniforge install exited with code $($proc.ExitCode)" }
    Write-OK "Miniforge installed: $CondaDir"
}

# -- 2. Unpack conda environment -----------------------------------------------
Write-Info "[2/6] Unpacking conda environment..."
$PackedEnv = Join-Path $ScriptDir "spectrum_analyzer_env.tar.gz"
if (-not (Test-Path $PackedEnv)) { Write-Fail "Packed env not found: $PackedEnv" }

if (Test-Path $EnvDir) {
    Write-Warn "Conda environment already exists at $EnvDir -- skipping"
} else {
    New-Item -ItemType Directory -Path $EnvDir -Force | Out-Null
    Write-Info "  Decompressing environment (2-5 min)..."
    # tar.exe ships with Windows 10+ at C:\Windows\System32\tar.exe
    $tarExe = "$env:SystemRoot\System32\tar.exe"
    if (-not (Test-Path $tarExe)) { $tarExe = "tar" }
    & $tarExe -xzf $PackedEnv -C $EnvDir
    if ($LASTEXITCODE -ne 0) { Write-Fail "tar extraction failed" }

    Write-Info "  Relinking environment paths (conda-unpack)..."
    $unpackExe = Join-Path $EnvDir "Scripts\conda-unpack.exe"
    if (Test-Path $unpackExe) {
        & $unpackExe
        Write-OK "Environment relinked"
    } else {
        Write-Warn "conda-unpack.exe not found -- relinking skipped (may still work)"
    }
    Write-OK "Conda environment ready: $EnvDir"
}

# -- 3. Install pip packages from local wheels ---------------------------------
Write-Info "[3/6] Installing pip packages from local wheels..."
$WheelDir = Join-Path $ScriptDir "pip_wheels"
if (-not (Test-Path $WheelDir)) { Write-Fail "pip_wheels directory not found in bundle" }
$PipExe = Join-Path $EnvDir "Scripts\pip.exe"
& $PipExe install --no-index --find-links $WheelDir --no-warn-script-location $PipPackages
if ($LASTEXITCODE -ne 0) { Write-Fail "pip offline install failed" }
Write-OK "Pip packages installed"

# -- 4. Deploy application -----------------------------------------------------
Write-Info "[4/6] Deploying application to $InstallDir..."
New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
$AppSrc = Join-Path $ScriptDir "app"
if (-not (Test-Path $AppSrc)) { Write-Fail "app/ directory not found in bundle" }
Copy-Item -Path "$AppSrc\*" -Destination $InstallDir -Recurse -Force
# Remove __pycache__ directories
Get-ChildItem -Path $InstallDir -Filter "__pycache__" -Recurse -Directory |
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
Write-OK "Application deployed: $InstallDir"

# -- 5. Create launcher scripts -----------------------------------------------
Write-Info "[5/6] Creating launchers..."

# -- GUI launcher (opens PyQt6 desktop app) ------------------------------------
$LauncherBat = Join-Path $InstallDir "run_app.bat"
@"
@echo off
set "CONDA_PREFIX=$EnvDir"
set "PATH=$EnvDir;$EnvDir\Scripts;$EnvDir\Library\bin;%PATH%"
set "QT_QPA_PLATFORM_PLUGIN_PATH=$EnvDir\Library\plugins\platforms"
set "QT_QPA_FONTDIR=%WINDIR%\Fonts"
set "QT_LOGGING_RULES=*.debug=false;qt.qpa.fonts=false"
cd /d "$InstallDir"
"$EnvDir\python.exe" run.py %*
"@ | Set-Content -Path $LauncherBat -Encoding ASCII

# -- Web launcher (starts server silently + opens browser automatically) -------
# How it works:
#   1. A hidden PowerShell process polls http://localhost:8000 in the background
#   2. The server starts in the foreground (this window shows server logs)
#   3. As soon as the server responds, the browser opens automatically
#   4. Close the window (or Ctrl+C) to stop the server
$WebLauncherBat = Join-Path $InstallDir "run_web.bat"
@"
@echo off
title Spectrum Analyzer -- Web Server
color 0A
set "CONDA_PREFIX=$EnvDir"
set "PATH=$EnvDir;$EnvDir\Scripts;$EnvDir\Library\bin;%PATH%"
set "QT_QPA_PLATFORM=offscreen"
set "QT_QPA_FONTDIR=%WINDIR%\Fonts"
set "QT_LOGGING_RULES=*.debug=false;qt.qpa.fonts=false;qt.qpa.plugin=false"
cd /d "$InstallDir"

echo.
echo  ================================================
echo   Spectrum Analyzer  --  Web Interface
echo  ================================================
echo   Server starting at http://localhost:8000
echo   Browser will open automatically when ready.
echo   Close this window to stop the server.
echo  ================================================
echo.

:: Step 1 -- Launch browser opener as a detached background process.
::   Uses ping as a 5-second delay (no timeout.exe needed), then polls
::   localhost:8000 once per second until the server responds.
::   start /min runs it in a minimized window that closes when done.
start "" /min cmd /c "ping -n 6 127.0.0.1 >nul & powershell -NoProfile -Command ""for(`$i=0;`$i -lt 120;`$i++){try{(New-Object Net.WebClient).DownloadString('http://localhost:8000')|Out-Null;Start-Process 'http://localhost:8000';break}catch{Start-Sleep 1}}"" "

:: Step 2 -- Start server in foreground.
::   Server logs appear in this window.
::   Closing this window stops the server.
echo  Starting server...
echo.
"$EnvDir\python.exe" run.py --headless
"@ | Set-Content -Path $WebLauncherBat -Encoding ASCII

Write-OK "GUI launcher:  run_app.bat"
Write-OK "Web launcher:  run_web.bat  (auto-opens browser)"

# Add env to user PATH (permanent, no admin needed)
$userPath = [Environment]::GetEnvironmentVariable("PATH", "User")
$newEntry = "$EnvDir\Scripts;$EnvDir;$EnvDir\Library\bin"
if ($userPath -notlike "*$EnvDir*") {
    [Environment]::SetEnvironmentVariable("PATH", "$newEntry;$userPath", "User")
    Write-OK "User PATH updated (effective after new terminal)"
}

# -- 6. Create shortcuts -------------------------------------------------------
Write-Info "[6/6] Creating desktop and Start Menu shortcuts..."
$WshShell = New-Object -ComObject WScript.Shell

# Desktop: GUI shortcut
$DesktopLnk = Join-Path ([Environment]::GetFolderPath("Desktop")) "Spectrum Analyzer.lnk"
$Shortcut = $WshShell.CreateShortcut($DesktopLnk)
$Shortcut.TargetPath       = "cmd.exe"
$Shortcut.Arguments        = "/c `"$LauncherBat`""
$Shortcut.WorkingDirectory = $InstallDir
$Shortcut.Description      = "Spectrum Analyzer SDR GUI"
$Shortcut.WindowStyle      = 1
$Shortcut.Save()
Write-OK "Desktop shortcut (GUI):  $DesktopLnk"

# Desktop: Web shortcut
$WebDesktopLnk = Join-Path ([Environment]::GetFolderPath("Desktop")) "Spectrum Analyzer (Web).lnk"
$ShortcutWeb = $WshShell.CreateShortcut($WebDesktopLnk)
$ShortcutWeb.TargetPath       = "cmd.exe"
$ShortcutWeb.Arguments        = "/c `"$WebLauncherBat`""
$ShortcutWeb.WorkingDirectory = $InstallDir
$ShortcutWeb.Description      = "Spectrum Analyzer Web Interface -- opens in browser"
$ShortcutWeb.WindowStyle      = 1
$ShortcutWeb.Save()
Write-OK "Desktop shortcut (Web):  $WebDesktopLnk"

# Start Menu folder
$StartMenuDir = Join-Path ([Environment]::GetFolderPath("Programs")) "Spectrum Analyzer"
New-Item -ItemType Directory -Path $StartMenuDir -Force | Out-Null

# Start Menu: GUI
$StartLnk = Join-Path $StartMenuDir "Spectrum Analyzer.lnk"
$Shortcut2 = $WshShell.CreateShortcut($StartLnk)
$Shortcut2.TargetPath       = "cmd.exe"
$Shortcut2.Arguments        = "/c `"$LauncherBat`""
$Shortcut2.WorkingDirectory = $InstallDir
$Shortcut2.Description      = "Spectrum Analyzer SDR GUI"
$Shortcut2.WindowStyle      = 1
$Shortcut2.Save()

# Start Menu: Web
$WebStartLnk = Join-Path $StartMenuDir "Spectrum Analyzer (Web Interface).lnk"
$Shortcut3 = $WshShell.CreateShortcut($WebStartLnk)
$Shortcut3.TargetPath       = "cmd.exe"
$Shortcut3.Arguments        = "/c `"$WebLauncherBat`""
$Shortcut3.WorkingDirectory = $InstallDir
$Shortcut3.Description      = "Spectrum Analyzer Web Interface -- starts server and opens browser"
$Shortcut3.WindowStyle      = 1
$Shortcut3.Save()
Write-OK "Start Menu shortcuts created (GUI + Web Interface)"

# -- [7/7] Hardware Driver Installation
function Install-Driver-Inline($folder, $name, $url) {
    $p = Join-Path $ScriptDir $folder
    Write-Info "  Installing: $name"
    if (-not (Test-Path $p)) { Write-Warn "  Not found in bundle. Install manually: $url"; return }
    $infs = Get-ChildItem -Path $p -Filter "*.inf" -Recurse
    if ($infs.Count -eq 0) { Write-Warn "  No .inf files found. Install manually: $url"; return }
    foreach ($inf in $infs) {
        Write-Info "  -> $($inf.Name)"
        & pnputil /add-driver $inf.FullName /install 2>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) { Write-OK "     Installed OK" }
        else { Write-Warn "     pnputil exit $LASTEXITCODE (may already be installed)" }
    }
    Write-OK "$name driver ready -- plug in device anytime"
}

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  Hardware Driver Installation" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Select hardware driver to install:" -ForegroundColor White
Write-Host "    [1]  USRP   (X300 / B200 / B210)" -ForegroundColor Cyan
Write-Host "    [2]  PlutoSDR (ADALM-PLUTO)" -ForegroundColor Cyan
Write-Host "    [3]  HackRF One" -ForegroundColor Cyan
Write-Host "    [4]  All of the above" -ForegroundColor Cyan
Write-Host "    [S]  Skip (run install_drivers.bat any time later)" -ForegroundColor Gray
Write-Host ""
$drvChoice = (Read-Host "  Enter choice (1 / 2 / 3 / 4 / S)").Trim().ToUpper()
Write-Host ""
switch ($drvChoice) {
    "1" { Install-Driver-Inline "drivers\uhd"      "USRP (UHD)"  "https://files.ettus.com/manual/page_transport.html" }
    "2" { Install-Driver-Inline "drivers\plutosdr" "PlutoSDR"    "https://wiki.analog.com/university/tools/pluto/drivers/windows" }
    "3" { Install-Driver-Inline "drivers\hackrf"   "HackRF One"  "https://zadig.akeo.ie" }
    "4" {
             Install-Driver-Inline "drivers\uhd"      "USRP (UHD)"  "https://files.ettus.com/manual/page_transport.html"
             Install-Driver-Inline "drivers\plutosdr" "PlutoSDR"    "https://wiki.analog.com/university/tools/pluto/drivers/windows"
             Install-Driver-Inline "drivers\hackrf"   "HackRF One"  "https://zadig.akeo.ie"
    }
    "S"     { Write-Host "  Skipped. Run install_drivers.bat any time." -ForegroundColor Yellow }
    default { Write-Host "  Invalid choice. Run install_drivers.bat to retry." -ForegroundColor Yellow }
}

# -- Summary -------------------------------------------------------------------
Write-Section "INSTALLATION COMPLETE"
Write-Host ""
Write-Host "  Launch options:" -ForegroundColor White
Write-Host "    GUI app:            double-click  Spectrum Analyzer" -ForegroundColor Green
Write-Host "    Web interface:      double-click  Spectrum Analyzer (Web)" -ForegroundColor Green
Write-Host "                        -> server starts, browser opens automatically" -ForegroundColor Gray
Write-Host "    Start Menu:         Start > Spectrum Analyzer" -ForegroundColor Green
Write-Host "    Terminal (GUI):     run_app.bat" -ForegroundColor Green
Write-Host "    Terminal (Web):     run_web.bat" -ForegroundColor Green
Write-Host ""
Write-Host "  Add more hardware drivers later:" -ForegroundColor White
Write-Host "    double-click install_drivers.bat" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Verify:" -ForegroundColor White
Write-Host "    hackrf_info" -ForegroundColor Cyan
Write-Host "    SoapySDRUtil --find" -ForegroundColor Cyan
Write-Host ""
"""

# -- Windows double-click launcher for install.ps1 --------------------------
DRIVER_MENU_PS1 = r'''
# =============================================================================
#  Spectrum Analyzer -- Hardware Driver Installer
#  Works standalone OR called from install.ps1
#  Re-runnable: run any time to add more drivers
# =============================================================================
param(
    [string]$BundleDir = $PSScriptRoot
)
# Normalise: remove any trailing backslash that batch files may append
$BundleDir = $BundleDir.TrimEnd("\")

function Write-Section($msg) {
    Write-Host "`n$('=' * 60)" -ForegroundColor Cyan
    Write-Host "  $msg" -ForegroundColor Cyan
    Write-Host $('=' * 60) -ForegroundColor Cyan
}
function Write-OK($msg)   { Write-Host "[  OK]  $msg" -ForegroundColor Green  }
function Write-Info($msg) { Write-Host "[INFO]  $msg" -ForegroundColor Blue   }
function Write-Warn($msg) { Write-Host "[WARN]  $msg" -ForegroundColor Yellow }

# ── Auto-elevate to admin (pnputil requires it) ───────────────────────────────
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "Requesting Administrator privileges for driver installation..." -ForegroundColor Yellow
    $argList = "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`" -BundleDir `"$BundleDir`""
    Start-Process PowerShell -Verb RunAs -ArgumentList $argList
    exit
}

# ── Driver install function ───────────────────────────────────────────────────
function Install-HardwareDriver($driverFolder, $hardwareName, $manualUrl) {
    $driverPath = Join-Path $BundleDir $driverFolder
    Write-Info "Installing driver: $hardwareName"

    if (-not (Test-Path $driverPath)) {
        Write-Warn "  Driver folder not found: $driverFolder"
        Write-Warn "  Install manually: $manualUrl"
        return
    }

    $infFiles = Get-ChildItem -Path $driverPath -Filter "*.inf" -Recurse
    if ($infFiles.Count -eq 0) {
        Write-Warn "  No .inf files found in $driverFolder"
        Write-Warn "  Install manually: $manualUrl"
        return
    }

    $anyFailed = $false
    foreach ($inf in $infFiles) {
        Write-Info "  -> $($inf.Name)"
        $out = & pnputil /add-driver $inf.FullName /install 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-OK "     Installed OK"
        } else {
            Write-Warn "     pnputil exit $LASTEXITCODE -- may already be installed"
            $anyFailed = $true
        }
    }

    if (-not $anyFailed) {
        Write-OK "$hardwareName driver installed -- plug in device anytime"
    } else {
        Write-Warn "$hardwareName -- some files skipped (may already be present)"
    }
}

# ── Show driver selection menu ────────────────────────────────────────────────
Write-Section "Hardware Driver Installation"
Write-Host ""
Write-Host "  Select which hardware driver(s) to install:" -ForegroundColor White
Write-Host ""
Write-Host "    [1]  USRP   (Ettus Research X300 / B200 / B210)" -ForegroundColor Cyan
Write-Host "    [2]  PlutoSDR (ADALM-PLUTO)" -ForegroundColor Cyan
Write-Host "    [3]  HackRF One" -ForegroundColor Cyan
Write-Host "    [4]  All of the above" -ForegroundColor Cyan
Write-Host "    [S]  Skip  (install later by running install_drivers.bat)" -ForegroundColor Gray
Write-Host ""

$choice = Read-Host "  Enter choice (1 / 2 / 3 / 4 / S)"
$choice  = $choice.Trim().ToUpper()

switch ($choice) {

    "1" {
        Write-Section "Installing USRP Driver"
        Install-HardwareDriver "drivers\uhd"      "USRP (UHD)"  "https://files.ettus.com/manual/page_transport.html"
    }

    "2" {
        Write-Section "Installing PlutoSDR Driver"
        Install-HardwareDriver "drivers\plutosdr" "PlutoSDR"    "https://wiki.analog.com/university/tools/pluto/drivers/windows"
    }

    "3" {
        Write-Section "Installing HackRF Driver"
        Install-HardwareDriver "drivers\hackrf"   "HackRF One"  "https://zadig.akeo.ie"
    }

    "4" {
        Write-Section "Installing All Drivers"
        Install-HardwareDriver "drivers\uhd"      "USRP (UHD)"  "https://files.ettus.com/manual/page_transport.html"
        Install-HardwareDriver "drivers\plutosdr" "PlutoSDR"    "https://wiki.analog.com/university/tools/pluto/drivers/windows"
        Install-HardwareDriver "drivers\hackrf"   "HackRF One"  "https://zadig.akeo.ie"
    }

    "S" {
        Write-Host ""
        Write-Host "  Skipped. To install drivers later, run:" -ForegroundColor Yellow
        Write-Host "    $BundleDir\install_drivers.bat" -ForegroundColor Cyan
        Write-Host "  (works even after main installation is complete)" -ForegroundColor Gray
    }

    default {
        Write-Host "  Invalid choice '$choice' -- skipping driver install." -ForegroundColor Yellow
        Write-Host "  Run install_drivers.bat to try again." -ForegroundColor Gray
    }
}

Write-Host ""
Write-Host "  Driver installation done." -ForegroundColor Green
Write-Host "  You can run install_drivers.bat any time to install additional drivers." -ForegroundColor Gray
Write-Host ""
'''

UNINSTALL_PS1 = r'''
# =============================================================================
#  Spectrum Analyzer -- Windows Uninstaller
#  Removes all installed files, shortcuts, PATH entries, and conda environment.
#  Miniforge base installation is preserved (only the spectrum_analyzer env
#  is removed).
#  After uninstalling, run install.bat again for a clean reinstall.
# =============================================================================
#Requires -Version 5.0
Set-StrictMode -Version Latest
$ErrorActionPreference = "SilentlyContinue"

$AppName    = "spectrum_analyzer"
$EnvName    = "spectrum_analyzer"
$CondaDir   = "$env:USERPROFILE\miniforge3"
$EnvDir     = "$CondaDir\envs\$EnvName"
$InstallDir = "$env:USERPROFILE\$AppName"

function Write-Section($msg) {
    Write-Host "`n$('=' * 60)" -ForegroundColor Cyan
    Write-Host "  $msg" -ForegroundColor Cyan
    Write-Host $('=' * 60) -ForegroundColor Cyan
}
function Write-OK($msg)   { Write-Host "[  OK]  $msg" -ForegroundColor Green  }
function Write-Info($msg) { Write-Host "[INFO]  $msg" -ForegroundColor Blue   }
function Write-Warn($msg) { Write-Host "[WARN]  $msg" -ForegroundColor Yellow }

Write-Section "Spectrum Analyzer -- Uninstaller"
Write-Host ""
Write-Host "  This will remove:" -ForegroundColor White
Write-Host "    $InstallDir" -ForegroundColor Yellow
Write-Host "    $EnvDir" -ForegroundColor Yellow
Write-Host "    Desktop shortcuts" -ForegroundColor Yellow
Write-Host "    Start Menu entries" -ForegroundColor Yellow
Write-Host "    PATH entries" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Miniforge base ($CondaDir) will be KEPT." -ForegroundColor Gray
Write-Host ""

$confirm = Read-Host "  Type YES to confirm uninstall"
if ($confirm -ne "YES") {
    Write-Host "  Cancelled." -ForegroundColor Gray
    exit 0
}

Write-Host ""

# -- 1. Remove conda environment -----------------------------------------------
Write-Info "[1/5] Removing conda environment..."
if (Test-Path $EnvDir) {
    Remove-Item -Recurse -Force $EnvDir -ErrorAction SilentlyContinue
    Write-OK "Conda environment removed: $EnvDir"
} else {
    Write-Warn "Conda environment not found: $EnvDir"
}

# -- 2. Remove application files -----------------------------------------------
Write-Info "[2/5] Removing application files..."
if (Test-Path $InstallDir) {
    Remove-Item -Recurse -Force $InstallDir -ErrorAction SilentlyContinue
    Write-OK "Application removed: $InstallDir"
} else {
    Write-Warn "Application directory not found: $InstallDir"
}

# -- 3. Remove desktop shortcuts -----------------------------------------------
Write-Info "[3/5] Removing desktop shortcuts..."
$desktopDir = [Environment]::GetFolderPath("Desktop")
$shortcutsToRemove = @(
    "Spectrum Analyzer.lnk",
    "Spectrum Analyzer (Web).lnk"
)
foreach ($lnk in $shortcutsToRemove) {
    $path = Join-Path $desktopDir $lnk
    if (Test-Path $path) {
        Remove-Item -Force $path -ErrorAction SilentlyContinue
        Write-OK "Removed: $lnk"
    }
}

# -- 4. Remove Start Menu entries ----------------------------------------------
Write-Info "[4/5] Removing Start Menu entries..."
$startMenuDir = Join-Path ([Environment]::GetFolderPath("Programs")) "Spectrum Analyzer"
if (Test-Path $startMenuDir) {
    Remove-Item -Recurse -Force $startMenuDir -ErrorAction SilentlyContinue
    Write-OK "Start Menu folder removed"
} else {
    Write-Warn "Start Menu folder not found"
}

# -- 5. Clean up PATH entries --------------------------------------------------
Write-Info "[5/5] Cleaning up PATH entries..."
$currentPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if ($currentPath) {
    $pathsToRemove = @(
        "$EnvDir",
        "$EnvDir\Scripts",
        "$EnvDir\Library\bin"
    )
    $cleanedPath = ($currentPath -split ';' |
        Where-Object { $_ -and ($pathsToRemove -notcontains $_) }) -join ';'
    [Environment]::SetEnvironmentVariable("PATH", $cleanedPath, "User")
    Write-OK "PATH cleaned"
}

# -- Done ----------------------------------------------------------------------
Write-Section "UNINSTALL COMPLETE"
Write-Host ""
Write-Host "  Spectrum Analyzer has been removed." -ForegroundColor Green
Write-Host ""
Write-Host "  To reinstall, run install.bat from the bundle folder." -ForegroundColor White
Write-Host ""
Write-Host "  Miniforge is still installed at: $CondaDir" -ForegroundColor Gray
Write-Host "  To remove it too: Remove-Item -Recurse -Force $CondaDir" -ForegroundColor Gray
Write-Host ""
pause
'''

CHECK_PS1 = '''
# =============================================================================
#  Spectrum Analyzer -- Dependency Checker
#  Verifies every component needed to run the app is correctly installed.
#  Run this any time to diagnose problems.
# =============================================================================
#Requires -Version 5.0
Set-StrictMode -Version Latest
$ErrorActionPreference = "SilentlyContinue"

$AppName  = "spectrum_analyzer"
$EnvName  = "spectrum_analyzer"
$CondaDir = "$env:USERPROFILE\\miniforge3"
$EnvDir   = "$CondaDir\\envs\\$EnvName"
$PyExe    = "$EnvDir\\python.exe"
$InstDir  = "$env:USERPROFILE\\$AppName"

function Write-Section($msg) {
    Write-Host ""
    Write-Host ("=" * 60) -ForegroundColor Cyan
    Write-Host "  $msg" -ForegroundColor Cyan
    Write-Host ("=" * 60) -ForegroundColor Cyan
}
function Pass($msg)  { Write-Host "  [PASS]  $msg" -ForegroundColor Green  }
function Fail($msg)  { Write-Host "  [FAIL]  $msg" -ForegroundColor Red    }
function Warn($msg)  { Write-Host "  [WARN]  $msg" -ForegroundColor Yellow }
function Info($msg)  { Write-Host "  [INFO]  $msg" -ForegroundColor Gray   }

$failures = 0

# -- 1. Core installation paths -------------------------------------------
Write-Section "1. Installation Paths"

if (Test-Path $CondaDir) { Pass "Miniforge:          $CondaDir" }
else { Fail "Miniforge NOT found: $CondaDir"; $failures++ }

if (Test-Path $EnvDir)   { Pass "Conda env:          $EnvDir" }
else { Fail "Conda env NOT found: $EnvDir"; $failures++ }

if (Test-Path $PyExe)    { Pass "Python executable:  $PyExe" }
else { Fail "Python NOT found:   $PyExe"; $failures++ }

if (Test-Path "$InstDir\\run.py") { Pass "App source:         $InstDir\run.py" }
else { Fail "App source NOT found: $InstDir\run.py"; $failures++ }

# -- 2. Python packages ---------------------------------------------------
Write-Section "2. Python Packages"

if (-not (Test-Path $PyExe)) {
    Fail "Python not found -- skipping package checks"
} else {
    $packages = @(
        @{ name="numpy";      import="numpy"        },
        @{ name="scipy";      import="scipy"        },
        @{ name="PyQt6";      import="PyQt6.QtCore" },
        @{ name="pyqtgraph";  import="pyqtgraph"    },
        @{ name="SoapySDR";   import="SoapySDR"     },
        @{ name="matplotlib"; import="matplotlib"   },
        @{ name="fastapi";    import="fastapi"       },
        @{ name="uvicorn";    import="uvicorn"       },
        @{ name="websockets"; import="websockets"    }
    )
    foreach ($pkg in $packages) {
        $ver = & $PyExe -c "import $($pkg.import); print(getattr($($pkg.import).split('.')[0] | ForEach-Object { __import__($_, fromlist=['__version__']) }, '__version__', 'ok'))" 2>$null
        $code = "import importlib,sys; m=importlib.import_module('$($pkg.import)'); print(getattr(m,'__version__','installed'))"
        $ver = & $PyExe -c $code 2>$null
        if ($LASTEXITCODE -eq 0 -and $ver) {
            Pass "$($pkg.name.PadRight(14)) $ver"
        } else {
            Fail "$($pkg.name.PadRight(14)) NOT INSTALLED"
            $failures++
        }
    }
}

# -- 3. SDR Hardware detection --------------------------------------------
Write-Section "3. SDR Hardware"

$soapyUtil = "$EnvDir\\Library\\bin\\SoapySDRUtil.exe"
if (-not (Test-Path $soapyUtil)) { $soapyUtil = "SoapySDRUtil" }

$hackrfInfo = "$EnvDir\\Library\\bin\\hackrf_info.exe"
if (-not (Test-Path $hackrfInfo)) { $hackrfInfo = "hackrf_info" }

# SoapySDR device scan
$soapyOut = & $soapyUtil --find 2>&1
if ($soapyOut -match "driver=hackrf") {
    Pass "HackRF One          detected via SoapySDR"
} else {
    Warn "HackRF One          not detected (not connected or driver missing)"
}

if ($soapyOut -match "driver=uhd") {
    Pass "USRP (UHD)          detected via SoapySDR"
} else {
    Warn "USRP (UHD)          not detected (check Ethernet connection)"
}

if ($soapyOut -match "driver=plutosdr") {
    Pass "PlutoSDR            detected via SoapySDR"
} else {
    Warn "PlutoSDR            not detected (not connected or driver missing)"
}

# hackrf_info direct check
$hrf = & $hackrfInfo 2>&1
if ($hrf -match "Found HackRF") {
    Pass "hackrf_info         HackRF enumerated"
    Info "  $($hrf | Select-String 'Serial' | Select-Object -First 1)"
} else {
    Warn "hackrf_info         no device found (check USB cable)"
}

# -- 4. Shortcuts and launchers -------------------------------------------
Write-Section "4. Shortcuts and Launchers"

$desktop = [Environment]::GetFolderPath("Desktop")
$startMenu = Join-Path ([Environment]::GetFolderPath("Programs")) "Spectrum Analyzer"

if (Test-Path "$desktop\\Spectrum Analyzer.lnk")        { Pass "Desktop shortcut (GUI)" }
else { Warn "Desktop shortcut (GUI) missing -- run install.bat to fix" }

if (Test-Path "$desktop\\Spectrum Analyzer (Web).lnk")  { Pass "Desktop shortcut (Web)" }
else { Warn "Desktop shortcut (Web) missing -- run install.bat to fix" }

if (Test-Path "$InstDir\\run_app.bat")  { Pass "GUI launcher:       run_app.bat" }
else { Fail "GUI launcher missing: run_app.bat"; $failures++ }

if (Test-Path "$InstDir\\run_web.bat")  { Pass "Web launcher:       run_web.bat" }
else { Fail "Web launcher missing: run_web.bat"; $failures++ }

# -- 5. Port availability -------------------------------------------------
Write-Section "5. Port Check"

$portInUse = netstat -an 2>$null | Select-String ":8000.*LISTENING"
if ($portInUse) {
    Warn "Port 8000 is already in use -- web server may fail to start"
    Warn "Stop the existing process or change the port in run.py"
} else {
    Pass "Port 8000              available for web server"
}

# -- 6. Windows tar availability ------------------------------------------
Write-Section "6. System Tools"

$tarExe = "$env:SystemRoot\\System32\\tar.exe"
if (Test-Path $tarExe) { Pass "tar.exe                present (Windows 10 1803+)" }
else { Fail "tar.exe                NOT found -- need Windows 10 build 1803 or newer"; $failures++ }

$psVer = $PSVersionTable.PSVersion
if ($psVer.Major -ge 5) { Pass "PowerShell             v$psVer" }
else { Fail "PowerShell             v$psVer -- need 5.0 or newer"; $failures++ }

# -- Summary --------------------------------------------------------------
Write-Host ""
Write-Host ("=" * 60) -ForegroundColor Cyan
if ($failures -eq 0) {
    Write-Host "  ALL CHECKS PASSED -- Spectrum Analyzer is ready to run" -ForegroundColor Green
} else {
    Write-Host "  $failures CHECK(S) FAILED -- see [FAIL] items above" -ForegroundColor Red
    Write-Host "  Run install.bat to fix missing components" -ForegroundColor Yellow
}
Write-Host ("=" * 60) -ForegroundColor Cyan
Write-Host ""
pause
'''

CHECK_BAT = '''@echo off
:: Spectrum Analyzer -- Dependency Checker
:: Run this any time to verify all components are correctly installed.
echo.
echo  Spectrum Analyzer -- Dependency Check
echo  ========================================
echo  Checking all installed components...
echo.
set "SA_BUNDLE=%~dp0"
if "%SA_BUNDLE:~-1%"=="\" set "SA_BUNDLE=%SA_BUNDLE:~0,-1%"
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0check.ps1"
'''

CHECK_SH  = '''#!/usr/bin/env bash
# =============================================================================
#  Spectrum Analyzer -- Linux Dependency Checker
#  Verifies every component needed to run the app is correctly installed.
# =============================================================================
set -uo pipefail

APP_NAME="spectrum_analyzer"
CONDA_DIR="${HOME}/miniforge3"
ENV_DIR="${CONDA_DIR}/envs/${APP_NAME}"
PYTHON="${ENV_DIR}/bin/python"
INSTALL_DIR="${HOME}/${APP_NAME}"

G='\033[0;32m'; R='\033[0;31m'; Y='\033[1;33m'; B='\033[0;34m'
BOLD='\033[1m'; C='\033[0;36m'; NC='\033[0m'
PASS() { echo -e "  ${G}[PASS]${NC}  $*"; }
FAIL() { echo -e "  ${R}[FAIL]${NC}  $*"; ((FAILURES++)); }
WARN() { echo -e "  ${Y}[WARN]${NC}  $*"; }
INFO() { echo -e "  ${B}[INFO]${NC}  $*"; }
SECTION() { echo -e "\n${BOLD}${C}== $* ==${NC}"; }
FAILURES=0

# -- 1. Installation paths ------------------------------------------------
SECTION "1. Installation Paths"

[[ -d "$CONDA_DIR"        ]] && PASS "Miniforge:    $CONDA_DIR"         || FAIL "Miniforge NOT found: $CONDA_DIR"
[[ -d "$ENV_DIR"          ]] && PASS "Conda env:    $ENV_DIR"           || FAIL "Conda env NOT found: $ENV_DIR"
[[ -f "$PYTHON"           ]] && PASS "Python:       $PYTHON"            || FAIL "Python NOT found: $PYTHON"
[[ -f "$INSTALL_DIR/run.py" ]] && PASS "App source: $INSTALL_DIR/run.py" || FAIL "App NOT found: $INSTALL_DIR/run.py"

# -- 2. Python packages ---------------------------------------------------
SECTION "2. Python Packages"

if [[ ! -f "$PYTHON" ]]; then
    FAIL "Python not found -- skipping package checks"
else
    check_pkg() {
        local label="$1" mod="$2"
        local ver
        ver=$("$PYTHON" -c "import importlib,sys; m=importlib.import_module('$mod'); print(getattr(m,'__version__','installed'))" 2>/dev/null)
        if [[ $? -eq 0 && -n "$ver" ]]; then
            PASS "$(printf '%-16s' "$label") $ver"
        else
            FAIL "$(printf '%-16s' "$label") NOT INSTALLED"
        fi
    }
    check_pkg "numpy"       "numpy"
    check_pkg "scipy"       "scipy"
    check_pkg "PyQt6"       "PyQt6.QtCore"
    check_pkg "pyqtgraph"   "pyqtgraph"
    check_pkg "SoapySDR"    "SoapySDR"
    check_pkg "matplotlib"  "matplotlib"
    check_pkg "fastapi"     "fastapi"
    check_pkg "uvicorn"     "uvicorn"
    check_pkg "websockets"  "websockets"
fi

# -- 3. SDR hardware ------------------------------------------------------
SECTION "3. SDR Hardware"

SOAPY="${ENV_DIR}/bin/SoapySDRUtil"
HACKRF="${ENV_DIR}/bin/hackrf_info"

if [[ -x "$SOAPY" ]]; then
    SOAPY_OUT=$("$SOAPY" --find 2>/dev/null || true)
    echo "$SOAPY_OUT" | grep -q "driver=hackrf"    && PASS "HackRF One      detected" || WARN "HackRF One      not detected (not connected?)"
    echo "$SOAPY_OUT" | grep -q "driver=uhd"       && PASS "USRP (UHD)      detected" || WARN "USRP (UHD)      not detected (check Ethernet)"
    echo "$SOAPY_OUT" | grep -q "driver=plutosdr"  && PASS "PlutoSDR        detected" || WARN "PlutoSDR        not detected (not connected?)"
else
    WARN "SoapySDRUtil not found -- skipping hardware scan"
fi

if [[ -x "$HACKRF" ]]; then
    HRF_OUT=$("$HACKRF" 2>/dev/null || true)
    echo "$HRF_OUT" | grep -q "Found HackRF" && PASS "hackrf_info     HackRF enumerated" || WARN "hackrf_info     no device found (check USB)"
fi

# -- 4. Shortcuts and launchers -------------------------------------------
SECTION "4. Shortcuts and Launchers"

[[ -f "${HOME}/.local/bin/${APP_NAME}"                                 ]] && PASS "Terminal command:  spectrum_analyzer"         || WARN "Terminal command missing -- run install.sh"
[[ -f "${HOME}/.local/share/applications/${APP_NAME}.desktop"          ]] && PASS "App menu (GUI):    .desktop entry present"    || WARN "App menu (GUI) missing"
[[ -f "${HOME}/.local/share/applications/${APP_NAME}_web.desktop"      ]] && PASS "App menu (Web):    .desktop entry present"    || WARN "App menu (Web) missing"
[[ -f "${INSTALL_DIR}/run_app.sh"                                       ]] && PASS "GUI launcher:      run_app.sh"                || FAIL "GUI launcher missing"
[[ -f "${INSTALL_DIR}/run_web.sh"                                       ]] && PASS "Web launcher:      run_web.sh"                || FAIL "Web launcher missing"

# -- 5. udev rules --------------------------------------------------------
SECTION "5. HackRF udev Rules"

RULES="/etc/udev/rules.d/53-hackrf.rules"
[[ -f "$RULES" ]] && PASS "udev rules:        $RULES" || WARN "udev rules missing -- HackRF may need sudo. Run install.sh to fix"

groups "$USER" | grep -q "plugdev" && PASS "plugdev group:     $USER is member" || WARN "plugdev group:     $USER not in plugdev -- re-plug HackRF after running install.sh"

# -- 6. Port availability -------------------------------------------------
SECTION "6. Port Check"

if ss -tlnp 2>/dev/null | grep -q ":8000" || netstat -tlnp 2>/dev/null | grep -q ":8000"; then
    WARN "Port 8000 is already in use -- web server may fail to start"
else
    PASS "Port 8000:         available for web server"
fi

# -- Summary --------------------------------------------------------------
echo ""
echo -e "${BOLD}${C}=================================================${NC}"
if [[ $FAILURES -eq 0 ]]; then
    echo -e "  ${G}ALL CHECKS PASSED -- Spectrum Analyzer is ready${NC}"
else
    echo -e "  ${R}$FAILURES CHECK(S) FAILED -- see [FAIL] items above${NC}"
    echo -e "  ${Y}Run install.sh to fix missing components${NC}"
fi
echo -e "${BOLD}${C}=================================================${NC}"
echo ""
'''

UNINSTALL_BAT = r'''@echo off
:: Spectrum Analyzer -- Uninstaller launcher
:: Double-click to uninstall Spectrum Analyzer.
:: After uninstalling, run install.bat again for a clean reinstall.
echo.
echo  Spectrum Analyzer Uninstaller
echo  ================================
echo  This will remove Spectrum Analyzer from this machine.
echo  You can reinstall it any time by running install.bat again.
echo.
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0uninstall.ps1"
'''

UNINSTALL_SH  = r'''#!/usr/bin/env bash
# =============================================================================
#  Spectrum Analyzer -- Linux Uninstaller
#  Removes all installed files, shortcuts, and the conda environment.
#  Miniforge base is preserved.
#  After uninstalling, run install.sh again for a clean reinstall.
# =============================================================================
set -euo pipefail

APP_NAME="spectrum_analyzer"
ENV_NAME="spectrum_analyzer"
CONDA_DIR="${HOME}/miniforge3"
ENV_DIR="${CONDA_DIR}/envs/${ENV_NAME}"
INSTALL_DIR="${HOME}/${APP_NAME}"

R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'; B='\033[0;34m'; C='\033[0;36m'
BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${B}[INFO]${NC}  $*"; }
ok()      { echo -e "${G}[  OK]${NC}  $*"; }
warn()    { echo -e "${Y}[WARN]${NC}  $*"; }
section() { echo -e "\n${BOLD}${C}==  $*  ==${NC}\n"; }

section "Spectrum Analyzer -- Uninstaller"
echo ""
echo "  This will remove:"
echo -e "    ${Y}${INSTALL_DIR}${NC}"
echo -e "    ${Y}${ENV_DIR}${NC}"
echo -e "    ${Y}Desktop shortcuts and app menu entries${NC}"
echo -e "    ${Y}Terminal command (~/.local/bin/spectrum_analyzer)${NC}"
echo -e "    ${Y}Systemd user service${NC}"
echo ""
echo -e "  Miniforge base (${CONDA_DIR}) will be ${G}KEPT${NC}."
echo ""
read -rp "  Type YES to confirm: " confirm
[[ "$confirm" == "YES" ]] || { echo "  Cancelled."; exit 0; }
echo ""

# -- 1. Stop and remove systemd service ---------------------------------------
info "[1/6] Removing systemd service..."
systemctl --user stop     ${APP_NAME} 2>/dev/null || true
systemctl --user disable  ${APP_NAME} 2>/dev/null || true
rm -f "${HOME}/.config/systemd/user/${APP_NAME}.service"
systemctl --user daemon-reload 2>/dev/null || true
ok "Systemd service removed"

# -- 2. Remove conda environment ----------------------------------------------
info "[2/6] Removing conda environment..."
if [[ -d "$ENV_DIR" ]]; then
    rm -rf "$ENV_DIR"
    ok "Conda environment removed: $ENV_DIR"
else
    warn "Conda environment not found: $ENV_DIR"
fi

# -- 3. Remove application files ----------------------------------------------
info "[3/6] Removing application files..."
if [[ -d "$INSTALL_DIR" ]]; then
    rm -rf "$INSTALL_DIR"
    ok "Application removed: $INSTALL_DIR"
else
    warn "Application directory not found: $INSTALL_DIR"
fi

# -- 4. Remove terminal command -----------------------------------------------
info "[4/6] Removing terminal command..."
rm -f "${HOME}/.local/bin/${APP_NAME}"
ok "Terminal command removed"

# -- 5. Remove desktop shortcuts and app menu entries -------------------------
info "[5/6] Removing desktop shortcuts and app menu..."
rm -f "${HOME}/.local/share/applications/${APP_NAME}.desktop"
rm -f "${HOME}/.local/share/applications/${APP_NAME}_web.desktop"
rm -f "${HOME}/Desktop/Spectrum Analyzer.desktop"
rm -f "${HOME}/Desktop/Spectrum Analyzer (Web).desktop"
rm -f "${HOME}/.local/share/icons/hicolor/scalable/apps/${APP_NAME}.svg"
update-desktop-database "${HOME}/.local/share/applications" 2>/dev/null || true
gtk-update-icon-cache -f -t "${HOME}/.local/share/icons/hicolor" 2>/dev/null || true
ok "Desktop shortcuts and app menu entries removed"

# -- 6. Note about Miniforge --------------------------------------------------
info "[6/6] Miniforge base preserved at: ${CONDA_DIR}"

section "UNINSTALL COMPLETE"
echo -e "  ${G}Spectrum Analyzer has been fully removed.${NC}"
echo ""
echo "  To reinstall, run install.sh from the bundle folder."
echo ""
echo "  To also remove Miniforge:"
echo "    rm -rf ${CONDA_DIR}"
echo ""
'''

INSTALL_DRIVERS_BAT = r'''@echo off
:: Spectrum Analyzer -- Driver Installer (standalone, re-runnable)
:: Run this any time to install or add hardware drivers.
:: Works even after the main installation is already complete.
setlocal

net session >nul 2>&1
if %errorLevel% == 0 goto :run

echo Requesting Administrator privileges (required for driver install)...
powershell -Command "Start-Process cmd -Verb RunAs -ArgumentList '/c cd /d ""%~dp0"" && ""%~f0""'"
exit /b

:run
echo.
echo  Spectrum Analyzer -- Hardware Driver Installer
echo  ===============================================
echo  You can install drivers for USRP, PlutoSDR, or HackRF.
echo  Re-run this file any time to install additional hardware.
echo.
set "SA_BUNDLE=%~dp0"
if "%SA_BUNDLE:~-1%"=="\" set "SA_BUNDLE=%SA_BUNDLE:~0,-1%"
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0install_drivers.ps1" -BundleDir "%SA_BUNDLE%"
echo.
pause
'''

INSTALL_BAT = r"""@echo off
:: Spectrum Analyzer -- Windows installer launcher
:: Double-click this file. It requests Administrator rights automatically.
setlocal

:: Check if already running as admin
net session >nul 2>&1
if %errorLevel% == 0 goto :run_installer

:: Not admin -- re-launch elevated via PowerShell
echo Requesting Administrator privileges...
echo (Required to install the USRP UHD USB driver)
echo.
powershell -Command "Start-Process cmd -Verb RunAs -ArgumentList '/c cd /d ""%~dp0"" && ""%~f0""'"
exit /b

:run_installer
echo.
echo  Spectrum Analyzer Installer
echo  ============================
echo  Running with Administrator privileges.
echo  PowerShell window will show installation progress.
echo.
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0install.ps1"
echo.
echo Installation complete. Press any key to close.
pause > nul
"""# -- README bundled inside the zip ------------------------------------------
def _readme(target_os: str, arch: str) -> str:
    if target_os == "linux":
        install_cmd = "bash install.sh"
        run_cmd     = "spectrum_analyzer  (open a new terminal first)"
        headless    = "spectrum_analyzer --headless"
    else:
        install_cmd = "double-click install.bat  OR  right-click install.ps1 -> Run with PowerShell"
        run_cmd     = "double-click Spectrum Analyzer on Desktop  OR  run_app.bat"
        headless    = "run_app.bat --headless"

    return textwrap.dedent(f"""\
    Spectrum Analyzer -- Offline Installation Bundle
    ==========================================
    Platform : {target_os} / {arch}
    Built by : spectrum_analyzer_prepare.py

    CONTENTS
    --------
    Miniforge3-{target_os}-{arch}.*     Conda/Python installer
    spectrum_analyzer_env.tar.gz              Packed Python environment
    pip_wheels/                          FastAPI, uvicorn, websockets, ...
    app/                                 Spectrum Analyzer source code
    install.sh  / install.ps1            Platform installer scripts
    install.bat                          Windows double-click launcher

    INSTALL
    -------
    1. Extract (unzip) this archive to any folder.
    2. Run:  {install_cmd}
    3. Launch: {run_cmd}
       Headless: {headless}

    REQUIREMENTS ON TARGET MACHINE
    --------------------------------
    Linux   : bash, tar, awk  (always present -- NO Python or conda needed)
    Windows : PowerShell 5+ and Windows 10 / 11  (tar.exe is built in)

    HACKRF USB DRIVER
    -----------------
    Linux   : udev rules are installed automatically. Re-plug after install.
    Windows : Install WinUSB driver via Zadig (https://zadig.akeo.ie).
              Select "HackRF One" -> "WinUSB" -> Install Driver.
              This step requires internet or a separate Zadig download.
    """)


# ===========================================================================
#  HELPERS
# ===========================================================================

def _print(msg: str, colour: str = "") -> None:
    COLOURS = {"red": "\033[0;31m", "green": "\033[0;32m",
               "yellow": "\033[1;33m", "blue": "\033[0;34m",
               "cyan": "\033[0;36m", "bold": "\033[1m"}
    NC = "\033[0m"
    prefix = COLOURS.get(colour, "")
    # Windows cmd doesn't support ANSI unless enabled; strip on Windows
    if sys.platform == "win32":
        print(msg)
    else:
        print(f"{prefix}{msg}{NC}")


def info(msg):    _print(f"[INFO]  {msg}", "blue")
def ok(msg):      _print(f"[  OK]  {msg}", "green")
def warn(msg):    _print(f"[WARN]  {msg}", "yellow")
def section(msg): _print(f"\n==  {msg}  ==\n", "cyan")
def die(msg):     _print(f"[FAIL]  {msg}", "red"); sys.exit(1)


def download(url: str, dest: Path, label: str = "") -> None:
    """Download url -> dest with a simple progress indicator."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    label = label or dest.name
    info(f"Downloading {label} ...")
    try:
        with urllib.request.urlopen(url, timeout=120) as resp:
            total = int(resp.headers.get("Content-Length", 0))
            downloaded = 0
            with open(dest, "wb") as f:
                while chunk := resp.read(1 << 16):   # 64 KB chunks
                    f.write(chunk)
                    downloaded += len(chunk)
                    if total:
                        pct = downloaded * 100 // total
                        print(f"\r  {pct:3d}%  {downloaded >> 20} MB / {total >> 20} MB",
                              end="", flush=True)
        print()  # newline after progress
        ok(f"Downloaded: {dest.name}  ({dest.stat().st_size >> 20} MB)")
    except urllib.error.URLError as exc:
        die(f"Download failed: {url}\n  {exc}")


def run_cmd(cmd: list, **kwargs) -> subprocess.CompletedProcess:
    """Run a subprocess, raising on failure."""
    return subprocess.run(cmd, check=True, **kwargs)


def _miniforge_url(target_os: str, arch: str) -> tuple[str, str]:
    """Return (url, filename) for the Miniforge installer."""
    v = MINIFORGE_VERSION
    if target_os == "windows":
        name = f"Miniforge3-{v}-Windows-x86_64.exe"
    else:
        name = f"Miniforge3-{v}-Linux-{arch}.sh"
    url = (f"https://github.com/conda-forge/miniforge/releases/download/{v}/{name}")
    return url, name



def _win_build_root() -> Path:
    """
    Return a short, guaranteed-space-free build root on Windows.

    The NSIS installer /D= flag silently fails (exit code 2) when the install
    path contains spaces, or when Python passes it as a quoted shell token.
    We avoid both by keeping all Windows build artefacts under
    %USERPROFILE%\\fa_build -- a short path with no spaces.
    """
    return Path(os.environ.get("USERPROFILE", "C:\\")) / "fa_build"


def _ensure_mamba(work: Path, mf_installer: Path, target_os: str) -> Path:
    """
    Install a temporary Miniforge and return the path to the mamba binary.

    Windows notes
    -------------
    The Miniforge .exe is an NSIS installer with two strict rules:
      1. /D= must be the VERY LAST argument on the command line.
      2. The path after /D= must NOT be quoted (even with spaces).
    Python subprocess list-form automatically quotes arguments, triggering
    exit code 2.  We fix this two ways:
      a. shell=True so the command string reaches NSIS verbatim.
      b. tmp_conda lives under %USERPROFILE%\\fa_build\\tmp_conda -
         guaranteed no spaces, regardless of where the project folder is.
    """
    if target_os == "windows":
        # Short, space-free path regardless of where the project lives
        tmp_conda = _win_build_root() / "tmp_conda"
    else:
        tmp_conda = work / "tmp_conda"

    if not tmp_conda.exists():
        info("Bootstrapping temporary Miniforge for package operations...")
        tmp_conda.parent.mkdir(parents=True, exist_ok=True)

        if target_os == "windows":
            # Use shell=True + raw string so Python never quotes the /D= path
            install_cmd = (
                f'"{mf_installer}" /S /InstallationType=JustMe '
                f'/RegisterPython=0 /D={tmp_conda}'
            )
            info(f"  Running: {install_cmd}")
            result = subprocess.run(install_cmd, shell=True)
            if result.returncode not in (0, 3010):  # 3010 = reboot needed (harmless)
                die(
                    f"Miniforge installer failed (exit code {result.returncode}).\n"
                    f"  Install path tried: {tmp_conda}\n"
                    f"  Ensure the path exists and contains no spaces."
                )
        else:
            run_cmd(["bash", str(mf_installer), "-b", "-p", str(tmp_conda), "-f"])

        ok(f"Temporary Miniforge at {tmp_conda}")
    else:
        warn(f"Temporary Miniforge already exists at {tmp_conda}, skipping")

    if target_os == "windows":
        mamba = tmp_conda / "Scripts" / "mamba.exe"
    else:
        mamba = tmp_conda / "bin" / "mamba"

    if not mamba.exists():
        die(
            f"mamba not found at {mamba}\n"
            f"  The Miniforge installation likely failed silently.\n"
            f"  Delete {tmp_conda} and run the script again."
        )

    # Ensure conda-pack is available in the temporary base env
    info("Ensuring conda-pack is in the temporary base environment...")
    run_cmd([str(mamba), "install", "-y", "-n", "base",
             "-c", "conda-forge", "conda-pack", "--quiet"])
    return mamba


# ===========================================================================
#  MAIN PREPARE LOGIC
# ===========================================================================


# -- Unicode -> ASCII sanitiser for embedded script templates -----------------
# PowerShell and bash both fail on box-drawing / dash Unicode characters when
# the file encoding is not declared.  Replace every non-ASCII char with a safe
# ASCII equivalent before writing templates into the ZIP.
_UNICODE_MAP = str.maketrans({
    '\u2014': '-',   # em dash        -
    '\u2013': '-',   # en dash        -
    '\u2012': '-',   # figure dash
    '\u2010': '-',   # hyphen
    '\u2500': '-',   # box light horiz -
    '\u2501': '-',   # box heavy horiz
    '\u2550': '=',   # box double horiz =
    '\u2502': '|',   # box light vert
    '\u2551': '|',   # box double vert
    '\u2018': "'",   # left single quote
    '\u2019': "'",   # right single quote
    '\u201c': '"',   # left double quote
    '\u201d': '"',   # right double quote
    '\u2026': '...', # ellipsis
    '\u00e2': '',    # garbage from bad re-encode
})

def _ascii(text: str) -> str:
    """Replace every known Unicode decoration with plain ASCII."""
    text = text.translate(_UNICODE_MAP)
    # Catch anything else above 0x7F with a fallback
    return text.encode('ascii', errors='replace').decode('ascii').replace('?', '-')

# UTF-8 BOM -- tells PowerShell the file is UTF-8, preventing misread of any
# remaining special bytes.
_UTF8_BOM = '\ufeff'

def _extract_all_drivers(tmp_env: Path, work: Path, target_os: str) -> None:
    """
    Extract Windows USB driver files for all three hardware types from the
    conda environment into drivers/<hardware>/ folders inside the bundle.

    Layout inside the zip:
        drivers/uhd/       <- USRP X300/B200  (pnputil installable)
        drivers/hackrf/    <- HackRF One       (pnputil installable)
        drivers/plutosdr/  <- PlutoSDR         (pnputil installable)

    On Linux, udev rules are written by install.sh directly (no files needed).

    Known conda env paths (Windows):
        UHD:      Library/share/uhd/usbdriver/
        HackRF:   Library/share/hackrf/        (may not exist - falls back to Zadig note)
        PlutoSDR: Library/share/libiio/        (libiio Windows driver inf files)
    """
    if target_os != "windows":
        return

    drivers_root = work / "drivers"
    drivers_root.mkdir(exist_ok=True)

    # Each entry: (subfolder_in_bundle, paths_to_try_in_env, display_name)
    driver_specs = [
        (
            "uhd",
            [
                tmp_env / "Library" / "share" / "uhd" / "usbdriver",
                tmp_env / "Library" / "uhd" / "usbdriver",
            ],
            "USRP (UHD)",
        ),
        (
            "hackrf",
            [
                tmp_env / "Library" / "share" / "hackrf",
                tmp_env / "Library" / "drivers" / "hackrf",
                tmp_env / "Library" / "share" / "libhackrf",
            ],
            "HackRF One",
        ),
        (
            "plutosdr",
            [
                tmp_env / "Library" / "share" / "libiio",
                tmp_env / "Library" / "share" / "ad9361",
                tmp_env / "Library" / "drivers" / "libiio",
            ],
            "PlutoSDR (libiio)",
        ),
    ]

    for subfolder, search_paths, display_name in driver_specs:
        dst = drivers_root / subfolder
        found_src = None
        for candidate in search_paths:
            if candidate.exists() and list(candidate.rglob("*.inf")):
                found_src = candidate
                break

        if found_src is None:
            warn(f"{display_name}: driver .inf files not found in conda env")
            warn(f"  Searched: {[str(p) for p in search_paths]}")
            warn(f"  Users will be directed to install manually.")
            # Create empty marker so install_drivers.ps1 shows the fallback URL
            dst.mkdir(exist_ok=True)
            dst.mkdir(exist_ok=True)
            note = display_name + " driver files not found. Install from vendor website."
            (dst / "NOT_FOUND.txt").write_text(note)
        else:
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(found_src, dst)
            inf_count = len(list(dst.rglob("*.inf")))
            ok(f"{display_name}: {inf_count} .inf files -> drivers/{subfolder}/")


def cmd_prepare(args) -> None:
    target_os = "windows" if sys.platform == "win32" else "linux"
    arch      = args.arch
    work      = Path(args.workdir).resolve()
    out_zip   = Path(args.outdir).resolve() / f"spectrum_analyzer_bundle_{target_os}_{arch}.zip"

    section(f"PREPARE -- building offline bundle for {target_os}/{arch}")
    info(f"Build workspace : {work}")
    info(f"Output archive  : {out_zip}")

    if args.clean and work.exists():
        warn(f"--clean: removing {work}")
        shutil.rmtree(work)

    work.mkdir(parents=True, exist_ok=True)
    (work / "pip_wheels").mkdir(exist_ok=True)

    # -- Step 1: Download Miniforge installer ---------------------------------
    section("Step 1/5 -- Downloading Miniforge installer")
    url, mf_name = _miniforge_url(target_os, arch)
    mf_path = work / mf_name
    if not mf_path.exists():
        download(url, mf_path, mf_name)
    else:
        warn(f"Already present: {mf_name}")

    # -- Step 2: Bootstrap temporary conda + create environment ---------------
    section("Step 2/5 -- Creating conda environment")
    mamba = _ensure_mamba(work, mf_path, target_os)

    # On Windows, keep tmp_env under the space-free fa_build root
    if target_os == "windows":
        tmp_env = _win_build_root() / "tmp_env"
    else:
        tmp_env = work / "tmp_env"
    if tmp_env.exists():
        warn("Removing existing tmp_env for clean build...")
        shutil.rmtree(tmp_env)

    info("Creating conda environment (resolving all packages -- 5-15 min)...")
    run_cmd([str(mamba), "create", "-y",
             "--prefix", str(tmp_env),
             *CONDA_CHANNELS,
             *CONDA_PACKAGES])
    ok("Conda environment created")

    # -- Step 2b: Extract UHD driver files for offline Windows installation
    _extract_all_drivers(tmp_env, work, target_os)

    # -- Step 3: Download pip wheels ------------------------------------------
    section("Step 3/5 -- Downloading pip wheels")
    if target_os == "windows":
        pip_exe = tmp_env / "Scripts" / "pip.exe"
    else:
        pip_exe = tmp_env / "bin" / "pip"

    run_cmd([str(pip_exe), "download",
             "--dest", str(work / "pip_wheels"),
             "--prefer-binary",
             *PIP_PACKAGES])
    ok("Pip wheels downloaded")

    # -- Step 4: conda-pack the environment -----------------------------------
    section("Step 4/5 -- Packing conda environment (3-10 min)")
    # Keep the packed env in the same space-free directory as tmp_env
    if target_os == "windows":
        packed_env = _win_build_root() / "spectrum_analyzer_env.tar.gz"
    else:
        packed_env = work / "spectrum_analyzer_env.tar.gz"
    if target_os == "windows":
        conda_pack_exe = _win_build_root() / "tmp_conda" / "Scripts" / "conda-pack.exe"
    else:
        conda_pack_exe = work / "tmp_conda" / "bin" / "conda-pack"

    run_cmd([str(conda_pack_exe),
             "--prefix", str(tmp_env),
             "--output", str(packed_env),
             "--force"])
    ok(f"Environment packed: {packed_env.stat().st_size >> 20} MB")

    # -- Step 5: Copy app source -----------------------------------------------
    section("Step 5/5 -- Copying application source")
    app_dest = work / "app"
    if app_dest.exists():
        shutil.rmtree(app_dest)
    # Exclude files that should not be in the bundle
    EXCLUDE = {
        ".git", "__pycache__", ".pytest_cache",
        "*.pyc", "*.pyo", "*.egg-info",
        args.workdir,                    # don't bundle the build workspace
        out_zip.name,
    }

    def _ignore(directory, contents):
        ignored = set()
        for item in contents:
            if item in EXCLUDE:
                ignored.add(item)
            if any(item.endswith(e.lstrip("*")) for e in EXCLUDE if e.startswith("*")):
                ignored.add(item)
        return ignored

    shutil.copytree(APP_SOURCE_DIR, app_dest, ignore=_ignore,
                    ignore_dangling_symlinks=True)
    # Remove this prepare script from the app copy
    for f in app_dest.glob("Spectrum_Analyzer.py"):
        f.unlink()
    ok(f"Application source copied ({sum(1 for _ in app_dest.rglob('*'))} files)")

    # -- Assemble the ZIP ------------------------------------------------------
    section("Assembling bundle ZIP")
    info(f"Output: {out_zip}")

    out_zip.parent.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED,
                         compresslevel=6) as zf:

        def _add(src: Path, arc_name: str) -> None:
            zf.write(src, arc_name)

        def _add_str(content: str, arc_name: str, mode: int = 0o644) -> None:
            info_obj = zipfile.ZipInfo(arc_name)
            info_obj.external_attr = (mode << 16)
            info_obj.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(info_obj, content)

        # Miniforge installer
        _add(mf_path, mf_name)
        info(f"  + {mf_name}")

        # Packed conda environment
        _add(packed_env, "spectrum_analyzer_env.tar.gz")
        info("  + spectrum_analyzer_env.tar.gz")

        # Pip wheels
        wheel_count = 0
        for whl in (work / "pip_wheels").iterdir():
            _add(whl, f"pip_wheels/{whl.name}")
            wheel_count += 1
        info(f"  + pip_wheels/  ({wheel_count} wheels)")

        # Hardware driver files (Windows only -- drivers/uhd/, /hackrf/, /plutosdr/)
        drivers_root = work / "drivers"
        if drivers_root.exists():
            drv_total = 0
            for hw_dir in sorted(drivers_root.iterdir()):
                if hw_dir.is_dir():
                    hw_count = 0
                    for f in hw_dir.rglob("*"):
                        if f.is_file():
                            arc = "drivers/" + hw_dir.name + "/" + str(f.relative_to(hw_dir)).replace(os.sep, "/")
                            _add(f, arc)
                            hw_count += 1
                    info(f"  + drivers/{hw_dir.name}/  ({hw_count} files)")
                    drv_total += hw_count
            info(f"  + drivers/  total {drv_total} files across {sum(1 for d in drivers_root.iterdir() if d.is_dir())} hardware types")

        # Application source
        file_count = 0
        for src in app_dest.rglob("*"):
            if src.is_file():
                arc = "app/" + str(src.relative_to(app_dest)).replace(os.sep, "/")
                _add(src, arc)
                file_count += 1
        info(f"  + app/  ({file_count} files)")

        # Installer scripts
        _add_str(_ascii(INSTALL_SH),    "install.sh",          mode=0o755)
        _add_str(_ascii(UNINSTALL_SH),  "uninstall.sh",        mode=0o755)
        _add_str(_ascii(CHECK_SH),      "check.sh",            mode=0o755)
        _add_str(_UTF8_BOM + _ascii(INSTALL_PS1),          "install.ps1",         mode=0o644)
        _add_str(_UTF8_BOM + _ascii(DRIVER_MENU_PS1),      "install_drivers.ps1", mode=0o644)
        _add_str(_UTF8_BOM + _ascii(UNINSTALL_PS1),        "uninstall.ps1",       mode=0o644)
        _add_str(_ascii(INSTALL_BAT),                       "install.bat",         mode=0o644)
        _add_str(_ascii(INSTALL_DRIVERS_BAT),               "install_drivers.bat", mode=0o644)
        _add_str(_ascii(UNINSTALL_BAT),                     "uninstall.bat",       mode=0o644)
        _add_str(_UTF8_BOM + _ascii(CHECK_PS1),             "check.ps1",           mode=0o644)
        _add_str(_ascii(CHECK_BAT),                         "check.bat",           mode=0o644)
        _add_str(_readme(target_os, arch), "README.txt", mode=0o644)
        info("  + install / uninstall / driver scripts added to bundle")
        info("  + install.sh / install.ps1 / install.bat / README.txt")

    size_mb = out_zip.stat().st_size >> 20
    ok("")
    ok("=" * 62)
    ok(f" Bundle ready: {out_zip.name}")
    ok(f" Size:         {size_mb} MB")
    ok("=" * 62)

    print()
    info("Transfer to the offline machine (USB drive, scp, etc.):")
    info(f"  {out_zip.name}")
    print()
    info("On the offline machine:")
    if target_os == "linux":
        info(f"  unzip {out_zip.name}")
        info("  cd spectrum_analyzer_bundle")
        info("  bash install.sh")
        print()
        info("After install (new terminal):")
        info("  spectrum_analyzer               # GUI")
        info("  spectrum_analyzer --headless    # web-only")
    else:
        info(f"  Unzip {out_zip.name}")
        info("  Double-click install.bat")
        info("     -- or -")
        info("  Right-click install.ps1 -> 'Run with PowerShell'")


# ===========================================================================
#  STATUS  (verify a previous installation on THIS machine)
# ===========================================================================

def cmd_status() -> None:
    section("Spectrum Analyzer -- Installation Status")
    is_win = sys.platform == "win32"
    home   = Path.home()

    if is_win:
        conda_dir   = home / "miniforge3"
        env_dir     = conda_dir / "envs" / ENV_NAME
        install_dir = home / APP_NAME
        launcher    = install_dir / "run_app.bat"
    else:
        conda_dir   = home / "miniforge3"
        env_dir     = conda_dir / "envs" / ENV_NAME
        install_dir = home / APP_NAME
        launcher    = home / ".local" / "bin" / APP_NAME

    G = "\033[0;32mv\033[0m"
    B = "\033[0;31mx\033[0m"

    def chk(label, path):
        mark = G if Path(path).exists() else B
        print(f"  {mark}  {label:40s} {path}")

    chk("Miniforge",             conda_dir)
    chk(f"Conda env '{ENV_NAME}'", env_dir)
    chk("Application (run.py)", install_dir / "run.py")
    chk("Launcher",              launcher)

    python = env_dir / ("python.exe" if is_win else "bin/python")
    if python.exists():
        print()
        print("Python packages:")
        packages = [
            ("numpy",      "numpy"),
            ("scipy",      "scipy"),
            ("PyQt6",      "PyQt6.QtCore"),
            ("pyqtgraph",  "pyqtgraph"),
            ("SoapySDR",   "SoapySDR"),
            ("fastapi",    "fastapi"),
            ("uvicorn",    "uvicorn"),
            ("websockets", "websockets"),
        ]
        check_code = (
            "import importlib, sys\n"
            "pkgs=" + repr(packages) + "\n"
            "for label, mod in pkgs:\n"
            "    try:\n"
            "        m=importlib.import_module(mod)\n"
            "        print(f'  \\033[0;32mv\\033[0m  {label:<18} {getattr(m,\"__version__\",\"ok\")}')\n"
            "    except ImportError:\n"
            "        print(f'  \\033[0;31mx\\033[0m  {label:<18} NOT FOUND')\n"
        )
        subprocess.run([str(python), "-c", check_code])
    else:
        warn("Python not found in conda env -- run install first")


# ===========================================================================
#  ENTRY POINT
# ===========================================================================

def main() -> None:
    host_os   = "windows" if sys.platform == "win32" else "linux"
    host_arch = "x86_64" if platform.machine() in ("x86_64", "AMD64") else "aarch64"

    parser = argparse.ArgumentParser(
        prog="spectrum_analyzer_prepare.py",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=textwrap.dedent("""\
            Build an offline installer bundle for Spectrum Analyzer.

            Run on an internet-connected machine.  Generates a ZIP that
            installs everything on an offline target with no pre-installed
            Python, conda, or internet access.

            NOTE: Build on the SAME platform as the target machine.
              Linux x86_64 machine  -> bundle for Linux x86_64 server/desktop
              Linux aarch64 machine -> bundle for Raspberry Pi 4/5
              Windows machine       -> bundle for Windows
        """),
        epilog=textwrap.dedent("""\
            Examples:
              python spectrum_analyzer_prepare.py
              python spectrum_analyzer_prepare.py --arch aarch64
              python spectrum_analyzer_prepare.py --clean --outdir /mnt/usb

            On offline Linux target:
              unzip spectrum_analyzer_bundle_linux_x86_64.zip
              bash install.sh

            On offline Windows target:
              Unzip -> double-click install.bat
        """),
    )
    sub = parser.add_subparsers(dest="command")

    p_prep = sub.add_parser("prepare", help="Download all deps and build bundle zip (default)")
    p_prep.add_argument("--arch",    default=host_arch,
                        choices=["x86_64", "aarch64"],
                        help=f"Target CPU architecture (default: {host_arch})")
    p_prep.add_argument("--outdir",  default=".", metavar="DIR",
                        help="Where to write the bundle zip (default: current dir)")
    p_prep.add_argument("--workdir", default=f".spectrum_analyzer_build",
                        metavar="DIR", help="Build workspace directory")
    p_prep.add_argument("--clean",   action="store_true",
                        help="Remove the build workspace before starting")

    sub.add_parser("status", help="Verify an existing installation on this machine")

    args = parser.parse_args()

    # Default to 'prepare' when no subcommand given
    if args.command is None:
        # Re-parse with prepare defaults
        args = parser.parse_args(["prepare"])

    if args.command == "prepare":
        # Validate Python version
        if sys.version_info < (3, 7):
            die("Python 3.7 or newer is required.")
        # Validate required tools
        missing = []
        if host_os == "linux":
            for tool in ("bash", "tar", "curl"):
                if not shutil.which(tool):
                    missing.append(tool)
        if missing:
            die(f"Required tools not found: {', '.join(missing)}\n"
                f"  Install with: sudo apt-get install {' '.join(missing)}")
        cmd_prepare(args)

    elif args.command == "status":
        cmd_status()


if __name__ == "__main__":
    main()